// This file is auto-generated by @hey-api/openapi-ts

export type UpdateUserMeRequest = {
    email?: string;
    name?: string;
    password?: string;
};

export type CreateUserRequest = {
    email: string;
    name: string;
    role: 'member' | 'owner';
    isServiceAccount: boolean;
};

export type UpdateUserRequest = {
    email: string;
    name: string;
    role: 'member' | 'owner';
    isDisabled: boolean;
};

export type CreatePersonalAccessTokenRequest = {
    name: string;
    profileId?: string | null;
};

export type UpdatePersonalAccessTokenRequest = {
    name?: string;
    profileId?: string | null;
};

export type CreateServerRequest = {
    name: string;
    slug: string;
    description?: string;
    logoUrl?: string;
    /**
     * The URL of the remote MCP server
     */
    url?: string;
    authorization: ServerAuthorization;
    transportConfig: HttpStreamingTransportConfig | HostedTransportConfig | StdioTransportConfig | SseTransportConfig;
};

export type ServerAuthorization = {
    method: 'none' | 'oauth' | 'apikey';
    credentialsScope: 'server' | 'user';
    apikeys?: Array<string>;
};

export type HttpStreamingTransportConfig = {
    type: 'httpstreaming';
    url: string;
    headers?: Array<[
        string,
        string
    ]>;
};

export type HostedTransportConfig = {
    type: 'hosted';
    runtime: 'node24';
    env?: Array<[
        string,
        string
    ]>;
};

export type StdioTransportConfig = {
    type: 'stdio';
    command: string;
    dockerImage?: string;
    env?: Array<[
        string,
        string
    ]>;
    transport: 'sse' | 'httpstreaming' | 'stdio';
    httpPort?: number | null;
    urlPath?: string | null;
};

export type SseTransportConfig = {
    type: 'sse';
    url: string;
    headers?: Array<[
        string,
        string
    ]>;
};

export type UpdateServerRequest = {
    name: string;
    slug: string;
    description?: string;
    logoUrl?: string;
    /**
     * The URL of the remote MCP server
     */
    url?: string;
    authorization: ServerAuthorization;
    transportConfig: HttpStreamingTransportConfig | HostedTransportConfig | StdioTransportConfig | SseTransportConfig | {
        type: 'self';
        id: string;
    };
    oauthMetadata?: {
        requiresAuthorization?: boolean;
        resource?: {
            id?: string;
            availableScopes?: Array<string>;
            metadataUrl?: string;
        } | null;
        as?: {
            issuer?: string;
            authorizeEndpoint?: string;
            deviceAuthorizationEndpoint?: string;
            tokenEndpoint?: string;
            extraAuthorizationParameters?: string;
            registrationEndpoint?: string;
            supportsPKCE?: boolean;
            supportedClientAuthMethods?: Array<string>;
            supportsDynamicClientRegistration?: boolean;
            noDynamicClientRegistrationReason?: string | null;
            serviceDocumentation?: string;
            metadataUrl?: string;
            availableScopes?: Array<string>;
        } | null;
    } | null;
    oauthClientConfiguration?: {
        clientId?: string;
        clientSecret?: string;
        grantType?: 'authorization_code' | 'device_code';
        clientAuthMethod?: 'client_secret_basic' | 'client_secret_post' | 'none' | string;
        scopes?: string;
    } | null;
};

export type ServerCredentialsOuth = {
    type: 'oauth';
    tokenSet: {
        accessToken: string;
        accessTokenExpiresAt?: number;
        idToken?: string;
        refreshToken?: string;
    };
};

export type ServerCredentialsApiKeys = {
    type: 'apikey';
    apikeys: Array<[
        string,
        string
    ]>;
};

export type AwsSecretsManagerConfiguration = {
    type: 'aws_secrets_manager';
    region: string;
    accessKeyId: string;
    secretAccessKey: string;
};

export type GcpSecretManagerConfiguration = {
    type: 'gcp_secret_manager';
    projectId: string;
    serviceAccountKey: string;
};

export type HashiCorpVaultConfiguration = {
    type: 'hashicorp_vault';
    address: string;
    token: string;
    namespace?: string;
    mountPath?: string;
};

export type InfisicalConfiguration = {
    type: 'infisical';
    siteUrl: string;
    accessToken: string;
    projectId: string;
    environment: string;
    secretPath: string;
};

export type AzureKeyVaultConfiguration = {
    type: 'azure_key_vault';
    vaultUrl: string;
    tenantId: string;
    clientId: string;
    clientSecret: string;
};

export type TestSecretRequest = {
    /**
     * The secret identifier (e.g., AWS ARN, GCP secret path, Vault path, or Infisical secret name)
     */
    secretIdentifier: string;
};

export type AuthMetadata = {
    isPlayground: boolean;
    user: {
        id: number;
        sub: string;
        tenantId: string;
        name: string;
        apiKey: string;
        email: string;
        role: 'member' | 'owner';
        isServiceAccount: boolean;
        createdAt: string;
        updatedAt: string;
        isSuperAdministrator?: boolean;
    };
    tenant: {
        id: string;
        isMcpAuthorizationApiKeyEnabled: boolean;
        grantUsersInstallServersPolicy: boolean;
        displayName: string;
        isTrial: boolean;
        subscriptionPlan: string;
        subscriptionSeats: number;
        numberOfEnabledUsers?: number;
        freeCredits: number;
        paidCredits: number;
    };
    rules: Array<unknown>;
    quota: {
        enabledServers: {
            quota: number;
            current: number;
            remaining: number;
        };
    };
};

export type AuditLogResponse = {
    readonly id: number;
    tenantId: string;
    eventTime: string;
    entityType: string | null;
    entityId: string | null;
    eventName: string;
    userId: number | null;
    details: unknown;
    onlySuperadminVisibility: boolean;
    createdAt: string;
    userFullName: string;
    userEmail: string | null;
    userSub: string | null;
    teamName: string | null;
    serverSlug: string | null;
};

export type PaginatedAuditLogs = {
    data: Array<AuditLogResponse>;
    pagination: {
        page: number;
        limit: number;
        total: number;
        totalPages: number;
        hasNext: boolean;
        hasPrev: boolean;
    };
};

export type GetUserMeResponse = {
    user: {
        id: number;
        sub: string;
        tenantId: string;
        name: string;
        email: string;
        role: 'member' | 'owner';
        isDisabled: boolean;
        isServiceAccount: boolean;
        createdAt: string;
        updatedAt: string;
    };
    identities: Array<UserIdentity>;
};

export type UserIdentity = {
    tenantId: number;
    externalId: string;
    userId: number;
    type: 'external-oidc' | 'external-saml' | 'native';
    createdAt: string;
    updatedAt: string;
};

export type User = {
    id: number;
    sub: string;
    tenantId: string;
    name: string;
    email: string;
    role: 'member' | 'owner';
    isSuperAdministrator: boolean;
    isDisabled: boolean;
    isServiceAccount: boolean;
    createdAt: string;
    updatedAt: string;
};

export type PersonalAccessToken = {
    tenantId: string;
    userId: number;
    id: string;
    name: string;
    apiKey: string;
    profileId: string | null;
    createdAt: string;
    lastUsedAt: string | null;
};

export type ServerOAuthClientConfiguration = {
    clientId: string;
    clientSecret: string;
    grantType: 'authorization_code' | 'device_code';
    clientAuthMethod: 'client_secret_basic' | 'client_secret_post' | 'none' | string;
    scopes: string;
};

export type ServerOAuthMetadata = {
    requiresAuthorization: boolean;
    resource?: {
        id: string;
        availableScopes: Array<string>;
        metadataUrl: string;
    };
    as?: {
        issuer: string;
        authorizeEndpoint: string;
        deviceAuthorizationEndpoint: string;
        tokenEndpoint: string;
        extraAuthorizationParameters: string;
        registrationEndpoint?: string;
        supportsPKCE: boolean;
        supportedClientAuthMethods: Array<string>;
        supportsDynamicClientRegistration: boolean;
        noDynamicClientRegistrationReason?: string | null;
        serviceDocumentation: string;
        metadataUrl: string;
        availableScopes: Array<string>;
    };
};

export type ServerCredentialsDto = {
    id: string;
    tenantId: string;
    scope: 'server' | 'user' | 'profile';
    userId: number | null;
    profileId: string | null;
    lastUsedAt: string | null;
    authorizedAt: string;
    type: 'oauth' | 'apikey';
    createdAt: string;
    updatedAt: string;
    userSub: string | null;
    userEmail: string | null;
    userName: string | null;
    profileName: string | null;
    apikeysPresent: Array<string> | null;
    hasAccessToken: boolean | null;
    accessTokenExpiry: string | null;
    hasRefreshToken: boolean | null;
    subject: string | null;
    email: string | null;
};

export type ServerDto = {
    id: number;
    slug: string;
    tenantId: string;
    name: string;
    description: string;
    logoUrl?: string;
    authorization: ServerAuthorizationOutput;
    transportConfig: HttpStreamingTransportConfigOutput | StdioTransportConfigOutput | SseTransportConfigOutput | {
        type: 'self';
        id: string;
    } | HostedTransportConfigOutput;
    oauthClientConfiguration: null | ServerOAuthClientConfiguration;
    oauthMetadata: null | ServerOAuthMetadata;
    isEnabled: boolean;
    lastToolRefreshAt: string | null;
    createdAt: string;
    updatedAt: string;
    serverCredentials: ServerCredentialsDto | null;
};

export type ServerFile = {
    tenantId: string;
    serverId: string;
    id: string;
    filename: string;
    sourceType: 'gcs' | 'aws-ssm' | 'aws-secrets-manager';
    sourceId: string;
    size: number | null;
    credentialId: string | null;
    createdAt: string;
    updatedAt: string;
};

export type ServerRunningStatusResponse = {
    isDeployed: boolean;
    isAvailable: boolean;
    isStabilizing: boolean;
    pods: Array<ServerPodStatus>;
};

export type ServerPodStatus = {
    name: string;
    ready: boolean;
    phase?: string;
    reason?: string;
    createdAt?: string;
};

export type McpServerTool = {
    tenantId: string;
    serverId: number;
    toolName: string;
    description: string;
    schema: {
        [key: string]: never;
    };
    outputSchema: {
        [key: string]: never;
    } | null;
    annotations: {
        [key: string]: never;
    } | null;
    isEnabled: boolean;
    createdAt: number;
    updatedAt: number;
};

export type GetMembersResponse = {
    teams: Array<{
        role: 'member' | 'admin' | 'maintainer';
        id: string;
        name: string;
    }>;
    users: Array<{
        role: 'member' | 'admin' | 'maintainer';
        sub: string;
        name: string;
        email: string;
    }>;
};

export type UploadSourceCodeResponse = {
    success: boolean;
    message: string;
    analysisResult?: unknown;
};

export type TenantDto = {
    id: string;
    isPlayground: boolean;
    displayName: string;
    upstreamOidcConfiguration: TenantOidcConfiguration | null;
    upstreamSamlConfiguration: TenantSamlConfiguration | null;
    isUpstreamOidcTokensTrusted: boolean;
    isAutomaticSeatIncreaseEnabled: boolean;
    isMcpAuthorizationApiKeyEnabled: boolean;
    grantPermissionsNewToolPolicy: boolean;
    allowMemberAddRemoteServers: boolean;
    allowMemberAddLocalServers: boolean;
    allowMemberAddHostedServers: boolean;
    memberDefaultRole: ('member' | 'admin' | 'maintainer') | 'none';
    mcpAuditLogLevel: McpAuditLogVerbosity;
};

export type TenantOidcConfiguration = {
    isEnabled: boolean;
    displayName: string;
    issuer: string;
    authorizeEndpoint: string;
    extraParameters: string;
    tokenEndpoint: string;
    userInfoEndpoint: string;
    introspectionEndpoint: string;
    jwksUri: string;
    clientId: string;
    clientSecret: string;
    clientAuthMethod: 'client_secret_basic' | 'client_secret_post';
    scopes: string;
};

export type TenantSamlConfiguration = {
    isEnabled: boolean;
    displayName: string;
    idpMetadataUrl: string;
    idpMetadataDocument: string;
    entryPoint: string;
    cert: string;
    identifierFormat: string;
    signatureAlgorithm: string;
    emailClaim: string;
    firstNameClaim: string;
    lastNameClaim: string;
};

export type McpAuditLogVerbosity = 'off' | 'terse' | 'detailed' | 'detailed-with-error' | 'verbose';

export type GetSubscriptionResponse = {
    subscriptionPlan: string;
    subscriptionSeats: number;
    subscription: {
        hasPaymentMethod: boolean;
        trialEndsAt: string | null;
        status: string;
        currentPeriodEnd: string;
        paymentType?: string | null;
        cancelsAt: string | null;
        perSeatAmount: number;
        currency: string;
        card: {
            valid: boolean;
            brand: string;
            last4: string;
            expiresYear: number;
            expiresMonth: number;
        } | null;
    } | null;
};

export type TeamWithMemberCount = {
    id: string;
    tenantId: string;
    name: string;
    description: string;
    createdAt: string;
    updatedAt: string;
    memberCount: number;
};

export type TeamMember = {
    teamId: string;
    userId: number;
    role: 'member' | 'maintainer';
    createdAt: string;
    updatedAt: string;
};

export type TeamInvitation = {
    id: string;
    teamId: string;
    tenantId: string;
    inviterUserId: number | null;
    email: string;
    role: 'member' | 'maintainer';
    token: string;
    expiresAt: string;
    acceptedAt: string | null;
    createdAt: string;
    updatedAt: string;
};

export type ServerMember = {
    tenantId: string;
    serverId: number;
    role: 'member' | 'admin' | 'maintainer';
    createdAt: string;
    updatedAt: string;
    userId: number;
    teamId: null;
} | {
    tenantId: string;
    serverId: number;
    role: 'member' | 'admin' | 'maintainer';
    createdAt: string;
    updatedAt: string;
    userId: null;
    teamId: string;
};

export type Server = {
    id: number;
    slug: string;
    tenantId: string;
    name: string;
    description: string;
    logoUrl?: string;
    authorization: ServerAuthorizationOutput;
    transportConfig: HttpStreamingTransportConfigOutput | StdioTransportConfigOutput | SseTransportConfigOutput | {
        type: 'self';
        id: string;
    } | HostedTransportConfigOutput;
    oauthClientConfiguration: null | ServerOAuthClientConfiguration;
    oauthMetadata: null | ServerOAuthMetadata;
    isEnabled: boolean;
    lastToolRefreshAt: string | null;
    createdAt: string;
    updatedAt: string;
};

export type TeamClaimMapping = {
    id: string;
    tenantId: string;
    teamId: string;
    claimKey: string;
    claimValue: string;
    createdAt: string;
};

export type SecretStoreListResponse = {
    stores: Array<SecretStoreResponse>;
};

export type SecretStoreResponse = {
    id: string;
    name: string;
    type: 'aws_secrets_manager' | 'gcp_secret_manager' | 'hashicorp_vault' | 'infisical' | 'azure_key_vault';
    isEnabled: boolean;
    createdAt: string;
    updatedAt: string;
};

export type SecretStoreDetailResponse = {
    id: string;
    name: string;
    type: 'aws_secrets_manager' | 'gcp_secret_manager' | 'hashicorp_vault' | 'infisical' | 'azure_key_vault';
    isEnabled: boolean;
    createdAt: string;
    updatedAt: string;
    configuration: AwsSecretsManagerConfigurationOutput | GcpSecretManagerConfigurationOutput | HashiCorpVaultConfigurationOutput | InfisicalConfigurationOutput | AzureKeyVaultConfigurationOutput;
};

export type SecretMappingListResponse = {
    mappings: Array<SecretMappingResponse>;
};

export type SecretMappingResponse = {
    name: string;
    secretIdentifier: string;
    createdAt: string;
    updatedAt: string;
};

export type TestSecretResponse = {
    success: boolean;
    message: string;
    value?: string;
};

export type Profile = {
    tenantId: string;
    id: string;
    createdBy: number;
    name: string;
    description: string;
    isOpenToAllUsers: boolean;
    isRestrictive: boolean;
    createdAt: string;
    updatedAt: string;
};

export type ProfileDetailsDto = {
    tenantId: string;
    id: string;
    createdBy: number;
    name: string;
    description: string;
    isOpenToAllUsers: boolean;
    isRestrictive: boolean;
    createdAt: string;
    updatedAt: string;
    servers: Array<{
        name: string;
        slug: string;
        authorization: ServerAuthorizationOutput;
        credentialsNumKeys: number | null;
        credentialScope: 'server' | 'user' | 'profile';
        credentials: ServerCredentialsDto | null;
    }>;
};

export type ProfileClaimMapping = {
    id: string;
    tenantId: string;
    profileId: string;
    claimKey: string;
    claimValue: string;
    createdAt: string;
};

export type ServerAuthorizationOutput = {
    method: 'none' | 'oauth' | 'apikey';
    credentialsScope: 'server' | 'user';
    apikeys?: Array<string>;
};

export type HttpStreamingTransportConfigOutput = {
    type: 'httpstreaming';
    url: string;
    headers?: Array<[
        string,
        string
    ]>;
};

export type StdioTransportConfigOutput = {
    type: 'stdio';
    command: string;
    dockerImage?: string;
    env?: Array<[
        string,
        string
    ]>;
    transport: 'sse' | 'httpstreaming' | 'stdio';
    httpPort?: number | null;
    urlPath?: string | null;
};

export type SseTransportConfigOutput = {
    type: 'sse';
    url: string;
    headers?: Array<[
        string,
        string
    ]>;
};

export type HostedTransportConfigOutput = {
    type: 'hosted';
    runtime: 'node24';
    env?: Array<[
        string,
        string
    ]>;
};

export type AwsSecretsManagerConfigurationOutput = {
    type: 'aws_secrets_manager';
    region: string;
    accessKeyId: string;
    secretAccessKey: string;
};

export type GcpSecretManagerConfigurationOutput = {
    type: 'gcp_secret_manager';
    projectId: string;
    serviceAccountKey: string;
};

export type HashiCorpVaultConfigurationOutput = {
    type: 'hashicorp_vault';
    address: string;
    token: string;
    namespace?: string;
    mountPath: string;
};

export type InfisicalConfigurationOutput = {
    type: 'infisical';
    siteUrl: string;
    accessToken: string;
    projectId: string;
    environment: string;
    secretPath: string;
};

export type AzureKeyVaultConfigurationOutput = {
    type: 'azure_key_vault';
    vaultUrl: string;
    tenantId: string;
    clientId: string;
    clientSecret: string;
};

export type AuditLogResponseWritable = {
    tenantId: string;
    eventTime: string;
    entityType: string | null;
    entityId: string | null;
    eventName: string;
    userId: number | null;
    details: unknown;
    onlySuperadminVisibility: boolean;
    createdAt: string;
    userFullName: string;
    userEmail: string | null;
    userSub: string | null;
    teamName: string | null;
    serverSlug: string | null;
};

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeResponses = {
    /**
     * Successful response
     */
    200: AuthMetadata;
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type GetAuditLogsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/audit-logs/{id}';
};

export type GetAuditLogsByIdResponses = {
    /**
     * Successful response
     */
    200: AuditLogResponse;
};

export type GetAuditLogsByIdResponse = GetAuditLogsByIdResponses[keyof GetAuditLogsByIdResponses];

export type GetAuditLogsData = {
    body?: never;
    path?: never;
    query?: {
        page?: string;
        limit?: string;
        userId?: string;
        entityTypes?: string | Array<string>;
        entityId?: string;
        tenantId?: string;
        startDate?: string;
        endDate?: string;
        search?: string;
    };
    url: '/audit-logs';
};

export type GetAuditLogsResponses = {
    /**
     * Successful response
     */
    200: PaginatedAuditLogs;
};

export type GetAuditLogsResponse = GetAuditLogsResponses[keyof GetAuditLogsResponses];

export type GetUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetUsersMeResponses = {
    /**
     * Successful response
     */
    200: GetUserMeResponse;
};

export type GetUsersMeResponse = GetUsersMeResponses[keyof GetUsersMeResponses];

export type PutUsersMeData = {
    body?: UpdateUserMeRequest;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type PutUsersMeResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PutUsersMeResponse = PutUsersMeResponses[keyof PutUsersMeResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: {
        type?: 'user' | 'service-account' | 'all';
    };
    url: '/users';
};

export type GetUsersResponses = {
    /**
     * Successful response
     */
    200: {
        users: Array<User>;
    };
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PostUsersData = {
    body?: CreateUserRequest;
    path?: never;
    query?: never;
    url: '/users';
};

export type PostUsersResponses = {
    /**
     * Successful response
     */
    200: {
        user: User;
    };
};

export type PostUsersResponse = PostUsersResponses[keyof PostUsersResponses];

export type DeleteUsersByUserSubData = {
    body?: never;
    path: {
        userSub: string;
    };
    query?: never;
    url: '/users/{userSub}';
};

export type DeleteUsersByUserSubResponses = {
    /**
     * Successful response
     */
    200: {
        [key: string]: never;
    };
};

export type DeleteUsersByUserSubResponse = DeleteUsersByUserSubResponses[keyof DeleteUsersByUserSubResponses];

export type GetUsersByUserSubData = {
    body?: never;
    path: {
        userSub: string;
    };
    query?: never;
    url: '/users/{userSub}';
};

export type GetUsersByUserSubResponses = {
    /**
     * Successful response
     */
    200: {
        user: User;
    };
};

export type GetUsersByUserSubResponse = GetUsersByUserSubResponses[keyof GetUsersByUserSubResponses];

export type PutUsersByUserSubData = {
    body?: UpdateUserRequest;
    path: {
        userSub: string;
    };
    query?: never;
    url: '/users/{userSub}';
};

export type PutUsersByUserSubResponses = {
    /**
     * Successful response
     */
    200: {
        user: User;
    };
};

export type PutUsersByUserSubResponse = PutUsersByUserSubResponses[keyof PutUsersByUserSubResponses];

export type GetUsersByUserSubPersonalAccessTokensData = {
    body?: never;
    path: {
        userSub: string;
    };
    query?: never;
    url: '/users/{userSub}/personal-access-tokens';
};

export type GetUsersByUserSubPersonalAccessTokensResponses = {
    /**
     * Successful response
     */
    200: {
        tokens: Array<PersonalAccessToken>;
    };
};

export type GetUsersByUserSubPersonalAccessTokensResponse = GetUsersByUserSubPersonalAccessTokensResponses[keyof GetUsersByUserSubPersonalAccessTokensResponses];

export type PostUsersByUserSubPersonalAccessTokensData = {
    body?: CreatePersonalAccessTokenRequest;
    path: {
        userSub: string;
    };
    query?: never;
    url: '/users/{userSub}/personal-access-tokens';
};

export type PostUsersByUserSubPersonalAccessTokensResponses = {
    /**
     * Successful response
     */
    200: {
        token: PersonalAccessToken;
    };
};

export type PostUsersByUserSubPersonalAccessTokensResponse = PostUsersByUserSubPersonalAccessTokensResponses[keyof PostUsersByUserSubPersonalAccessTokensResponses];

export type DeleteUsersByUserSubPersonalAccessTokensByPatIdData = {
    body?: never;
    path: {
        userSub: string;
        patId: string;
    };
    query?: never;
    url: '/users/{userSub}/personal-access-tokens/{patId}';
};

export type DeleteUsersByUserSubPersonalAccessTokensByPatIdResponses = {
    /**
     * Successful response
     */
    200: {
        [key: string]: never;
    };
};

export type DeleteUsersByUserSubPersonalAccessTokensByPatIdResponse = DeleteUsersByUserSubPersonalAccessTokensByPatIdResponses[keyof DeleteUsersByUserSubPersonalAccessTokensByPatIdResponses];

export type PatchUsersByUserSubPersonalAccessTokensByPatIdData = {
    body?: UpdatePersonalAccessTokenRequest;
    path: {
        userSub: string;
        patId: string;
    };
    query?: never;
    url: '/users/{userSub}/personal-access-tokens/{patId}';
};

export type PatchUsersByUserSubPersonalAccessTokensByPatIdResponses = {
    /**
     * Successful response
     */
    200: {
        [key: string]: never;
    };
};

export type PatchUsersByUserSubPersonalAccessTokensByPatIdResponse = PatchUsersByUserSubPersonalAccessTokensByPatIdResponses[keyof PatchUsersByUserSubPersonalAccessTokensByPatIdResponses];

export type GetMcpServersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/mcp-servers';
};

export type GetMcpServersResponses = {
    /**
     * Successful response
     */
    200: {
        servers: Array<{
            id: number;
            slug: string;
            tenantId: string;
            name: string;
            description: string;
            logoUrl?: string;
            authorization: ServerAuthorizationOutput;
            transportConfig: HttpStreamingTransportConfigOutput | StdioTransportConfigOutput | SseTransportConfigOutput | {
                type: 'self';
                id: string;
            } | HostedTransportConfigOutput;
            oauthClientConfiguration: null | ServerOAuthClientConfiguration;
            oauthMetadata: null | ServerOAuthMetadata;
            isEnabled: boolean;
            lastToolRefreshAt: string | null;
            createdAt: string;
            updatedAt: string;
            serverCredentials: ServerCredentialsDto | null;
            usage: {
                lastSevenDays: number;
            };
        }>;
    };
};

export type GetMcpServersResponse = GetMcpServersResponses[keyof GetMcpServersResponses];

export type PostMcpServersData = {
    body?: CreateServerRequest;
    path?: never;
    query?: never;
    url: '/mcp-servers';
};

export type PostMcpServersResponses = {
    /**
     * Successful response
     */
    200: {
        server: ServerDto;
        files: Array<ServerFile>;
        currentUserCredentials: ServerCredentialsDto | null;
    };
};

export type PostMcpServersResponse = PostMcpServersResponses[keyof PostMcpServersResponses];

export type DeleteMcpServersByServerSlugData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}';
};

export type DeleteMcpServersByServerSlugResponses = {
    /**
     * Successful response
     */
    200: {
        server: ServerDto;
        files: Array<ServerFile>;
        currentUserCredentials: ServerCredentialsDto | null;
    };
};

export type DeleteMcpServersByServerSlugResponse = DeleteMcpServersByServerSlugResponses[keyof DeleteMcpServersByServerSlugResponses];

export type GetMcpServersByServerSlugData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}';
};

export type GetMcpServersByServerSlugResponses = {
    /**
     * Successful response
     */
    200: {
        server: ServerDto;
        files: Array<ServerFile>;
        currentUserCredentials: ServerCredentialsDto | null;
    };
};

export type GetMcpServersByServerSlugResponse = GetMcpServersByServerSlugResponses[keyof GetMcpServersByServerSlugResponses];

export type PutMcpServersByServerSlugData = {
    body?: UpdateServerRequest;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}';
};

export type PutMcpServersByServerSlugResponses = {
    /**
     * Successful response
     */
    200: {
        server: ServerDto;
        files: Array<ServerFile>;
        currentUserCredentials: ServerCredentialsDto | null;
    };
};

export type PutMcpServersByServerSlugResponse = PutMcpServersByServerSlugResponses[keyof PutMcpServersByServerSlugResponses];

export type GetMcpServersByServerSlugRunningStatusData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/running-status';
};

export type GetMcpServersByServerSlugRunningStatusResponses = {
    /**
     * Successful response
     */
    200: ServerRunningStatusResponse;
};

export type GetMcpServersByServerSlugRunningStatusResponse = GetMcpServersByServerSlugRunningStatusResponses[keyof GetMcpServersByServerSlugRunningStatusResponses];

export type PutMcpServersByServerSlugConfigData = {
    body?: {
        type?: 'httpstreaming';
        url?: string;
        headers?: Array<[
            string,
            string
        ]>;
    } | {
        type?: 'hosted';
        runtime?: 'node24';
        env?: Array<[
            string,
            string
        ]>;
    } | {
        type?: 'stdio';
        command?: string;
        dockerImage?: string;
        env?: Array<[
            string,
            string
        ]>;
        transport?: 'sse' | 'httpstreaming' | 'stdio';
        httpPort?: number | null;
        urlPath?: string | null;
    } | {
        type?: 'sse';
        url?: string;
        headers?: Array<[
            string,
            string
        ]>;
    } | {
        type?: 'self';
        id?: string;
    };
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/config';
};

export type PutMcpServersByServerSlugConfigResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type PutMcpServersByServerSlugIsEnabledData = {
    body?: {
        value: boolean;
    };
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/isEnabled';
};

export type PutMcpServersByServerSlugIsEnabledResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PutMcpServersByServerSlugIsEnabledResponse = PutMcpServersByServerSlugIsEnabledResponses[keyof PutMcpServersByServerSlugIsEnabledResponses];

export type PutMcpServersByServerSlugAuthorizationData = {
    body?: {
        method: 'none' | 'oauth' | 'apikey';
        credentialsScope: 'server' | 'user';
        apikeys?: Array<string>;
    };
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/authorization';
};

export type PutMcpServersByServerSlugAuthorizationResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type GetMcpServersByServerSlugOauthDiscoverData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: {
        url?: string;
    };
    url: '/mcp-servers/{serverSlug}/oauth/discover';
};

export type GetMcpServersByServerSlugOauthDiscoverResponses = {
    /**
     * Successful response
     */
    200: {
        oauthMetadata: ServerOAuthMetadata | null;
    };
};

export type GetMcpServersByServerSlugOauthDiscoverResponse = GetMcpServersByServerSlugOauthDiscoverResponses[keyof GetMcpServersByServerSlugOauthDiscoverResponses];

export type GetMcpServersByServerSlugToolsData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/tools';
};

export type GetMcpServersByServerSlugToolsResponses = {
    /**
     * Successful response
     */
    200: {
        tools: Array<McpServerTool>;
    };
};

export type GetMcpServersByServerSlugToolsResponse = GetMcpServersByServerSlugToolsResponses[keyof GetMcpServersByServerSlugToolsResponses];

export type PutMcpServersByServerSlugAllToolsIsEnabledData = {
    body?: {
        value: boolean;
    };
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/all-tools-isEnabled';
};

export type PutMcpServersByServerSlugAllToolsIsEnabledResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
        message: string;
    };
};

export type PutMcpServersByServerSlugAllToolsIsEnabledResponse = PutMcpServersByServerSlugAllToolsIsEnabledResponses[keyof PutMcpServersByServerSlugAllToolsIsEnabledResponses];

export type PutMcpServersByServerSlugToolsByToolNameIsEnabledData = {
    body?: {
        value: boolean;
    };
    path: {
        serverSlug: string;
        toolName: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/tools/{toolName}/isEnabled';
};

export type PutMcpServersByServerSlugToolsByToolNameIsEnabledResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
        message: string;
    };
};

export type PutMcpServersByServerSlugToolsByToolNameIsEnabledResponse = PutMcpServersByServerSlugToolsByToolNameIsEnabledResponses[keyof PutMcpServersByServerSlugToolsByToolNameIsEnabledResponses];

export type PostMcpServersByServerSlugToolsByToolNameCallData = {
    body?: {
        args: {
            [key: string]: unknown;
        };
    };
    path: {
        serverSlug: string;
        toolName: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/tools/{toolName}/call';
};

export type PostMcpServersByServerSlugToolsByToolNameCallResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type PostToolsRefreshData = {
    body?: never;
    path?: never;
    query?: {
        serverSlug?: string;
    };
    url: '/tools/refresh';
};

export type PostToolsRefreshResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type GetMcpServersByServerSlugMembersData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/members/';
};

export type GetMcpServersByServerSlugMembersResponses = {
    /**
     * Successful response
     */
    200: GetMembersResponse;
};

export type GetMcpServersByServerSlugMembersResponse = GetMcpServersByServerSlugMembersResponses[keyof GetMcpServersByServerSlugMembersResponses];

export type DeleteMcpServersByServerSlugMembersByMemberTypeByMemberIdData = {
    body?: never;
    path: {
        serverSlug: string;
        memberType: 'users' | 'teams';
        memberId: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/members/{memberType}/{memberId}';
};

export type DeleteMcpServersByServerSlugMembersByMemberTypeByMemberIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type DeleteMcpServersByServerSlugMembersByMemberTypeByMemberIdResponse = DeleteMcpServersByServerSlugMembersByMemberTypeByMemberIdResponses[keyof DeleteMcpServersByServerSlugMembersByMemberTypeByMemberIdResponses];

export type PutMcpServersByServerSlugMembersByMemberTypeByMemberIdData = {
    body?: {
        role: 'member' | 'admin' | 'maintainer';
    };
    path: {
        serverSlug: string;
        memberType: 'users' | 'teams';
        memberId: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/members/{memberType}/{memberId}';
};

export type PutMcpServersByServerSlugMembersByMemberTypeByMemberIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PutMcpServersByServerSlugMembersByMemberTypeByMemberIdResponse = PutMcpServersByServerSlugMembersByMemberTypeByMemberIdResponses[keyof PutMcpServersByServerSlugMembersByMemberTypeByMemberIdResponses];

export type DeleteMcpServersByServerSlugCredentialsUserData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/credentials/user';
};

export type DeleteMcpServersByServerSlugCredentialsUserResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type GetMcpServersByServerSlugCredentialsUserData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/credentials/user';
};

export type GetMcpServersByServerSlugCredentialsUserResponses = {
    /**
     * Successful response
     */
    200: {
        credentials: ServerCredentialsDto | null;
    };
};

export type GetMcpServersByServerSlugCredentialsUserResponse = GetMcpServersByServerSlugCredentialsUserResponses[keyof GetMcpServersByServerSlugCredentialsUserResponses];

export type PutMcpServersByServerSlugCredentialsUserData = {
    body?: ServerCredentialsOuth | ServerCredentialsApiKeys;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/credentials/user';
};

export type PutMcpServersByServerSlugCredentialsUserResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PutMcpServersByServerSlugCredentialsUserResponse = PutMcpServersByServerSlugCredentialsUserResponses[keyof PutMcpServersByServerSlugCredentialsUserResponses];

export type DeleteMcpServersByServerSlugCredentialsServerData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/credentials/server';
};

export type DeleteMcpServersByServerSlugCredentialsServerResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type GetMcpServersByServerSlugCredentialsServerData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/credentials/server';
};

export type GetMcpServersByServerSlugCredentialsServerResponses = {
    /**
     * Successful response
     */
    200: {
        credentials: ServerCredentialsDto | null;
    };
};

export type GetMcpServersByServerSlugCredentialsServerResponse = GetMcpServersByServerSlugCredentialsServerResponses[keyof GetMcpServersByServerSlugCredentialsServerResponses];

export type PutMcpServersByServerSlugCredentialsServerData = {
    body?: ServerCredentialsOuth | ServerCredentialsApiKeys;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/credentials/server';
};

export type PutMcpServersByServerSlugCredentialsServerResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PutMcpServersByServerSlugCredentialsServerResponse = PutMcpServersByServerSlugCredentialsServerResponses[keyof PutMcpServersByServerSlugCredentialsServerResponses];

export type GetMcpServersByServerSlugCredentialsProfileData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query: {
        profileId: string;
    };
    url: '/mcp-servers/{serverSlug}/credentials/profile';
};

export type GetMcpServersByServerSlugCredentialsProfileResponses = {
    /**
     * Successful response
     */
    200: {
        credentials: ServerCredentialsDto | null;
    };
};

export type GetMcpServersByServerSlugCredentialsProfileResponse = GetMcpServersByServerSlugCredentialsProfileResponses[keyof GetMcpServersByServerSlugCredentialsProfileResponses];

export type GetMcpServersByServerSlugCredentialsUserApikeysData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/credentials/user/apikeys';
};

export type GetMcpServersByServerSlugCredentialsUserApikeysResponses = {
    /**
     * Successful response
     */
    200: {
        apikeys: Array<[
            string,
            string
        ]>;
    };
};

export type GetMcpServersByServerSlugCredentialsUserApikeysResponse = GetMcpServersByServerSlugCredentialsUserApikeysResponses[keyof GetMcpServersByServerSlugCredentialsUserApikeysResponses];

export type GetMcpServersByServerSlugCredentialsServerApikeysData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/credentials/server/apikeys';
};

export type GetMcpServersByServerSlugCredentialsServerApikeysResponses = {
    /**
     * Successful response
     */
    200: {
        apikeys: Array<[
            string,
            string
        ]>;
    };
};

export type GetMcpServersByServerSlugCredentialsServerApikeysResponse = GetMcpServersByServerSlugCredentialsServerApikeysResponses[keyof GetMcpServersByServerSlugCredentialsServerApikeysResponses];

export type GetMcpServersByServerSlugCredentialsProfileByProfileIdApikeysData = {
    body?: never;
    path: {
        serverSlug: string;
        profileId: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/credentials/profile/{profileId}/apikeys';
};

export type GetMcpServersByServerSlugCredentialsProfileByProfileIdApikeysResponses = {
    /**
     * Successful response
     */
    200: {
        apikeys: Array<[
            string,
            string
        ]>;
    };
};

export type GetMcpServersByServerSlugCredentialsProfileByProfileIdApikeysResponse = GetMcpServersByServerSlugCredentialsProfileByProfileIdApikeysResponses[keyof GetMcpServersByServerSlugCredentialsProfileByProfileIdApikeysResponses];

export type DeleteMcpServersByServerSlugCredentialsProfilesByProfileIdData = {
    body?: never;
    path: {
        serverSlug: string;
        profileId: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/credentials/profiles/{profileId}';
};

export type DeleteMcpServersByServerSlugCredentialsProfilesByProfileIdResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type PutMcpServersByServerSlugCredentialsProfilesByProfileIdData = {
    body?: ServerCredentialsOuth | ServerCredentialsApiKeys;
    path: {
        serverSlug: string;
        profileId: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/credentials/profiles/{profileId}';
};

export type PutMcpServersByServerSlugCredentialsProfilesByProfileIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PutMcpServersByServerSlugCredentialsProfilesByProfileIdResponse = PutMcpServersByServerSlugCredentialsProfilesByProfileIdResponses[keyof PutMcpServersByServerSlugCredentialsProfilesByProfileIdResponses];

export type PostMcpServersByServerSlugCredentialsCopyData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query: {
        /**
         * ID of the credentials to copy
         */
        id: string;
        /**
         * The scope to copy the credentials to
         */
        to: 'server' | 'user' | 'profile';
        /**
         * Target profile ID when copying to profile scope
         */
        profileId?: string;
        /**
         * Target user sub when copying to user scope which is not the currently authenticated user
         */
        userSub?: string;
    };
    url: '/mcp-servers/{serverSlug}/credentials/copy';
};

export type PostMcpServersByServerSlugCredentialsCopyResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PostMcpServersByServerSlugCredentialsCopyResponse = PostMcpServersByServerSlugCredentialsCopyResponses[keyof PostMcpServersByServerSlugCredentialsCopyResponses];

export type GetMcpServersByServerSlugCredentialsAuthorizeUrlData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: {
        scope?: 'server' | 'user' | 'profile';
        redirect?: 'true' | 'false';
        returnTo?: 'details' | 'settings' | 'thank-you-page' | 'profile';
        profileId?: string;
        userSub?: string;
    };
    url: '/mcp-servers/{serverSlug}/credentials/authorize-url';
};

export type GetMcpServersByServerSlugCredentialsAuthorizeUrlResponses = {
    /**
     * Successful response
     */
    200: {
        method: 'none' | 'oauth' | 'apikey';
        url?: string;
    };
};

export type GetMcpServersByServerSlugCredentialsAuthorizeUrlResponse = GetMcpServersByServerSlugCredentialsAuthorizeUrlResponses[keyof GetMcpServersByServerSlugCredentialsAuthorizeUrlResponses];

export type DeleteMcpServersByServerSlugCredentialsData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/credentials';
};

export type DeleteMcpServersByServerSlugCredentialsResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
        deletedCount: number;
    };
};

export type DeleteMcpServersByServerSlugCredentialsResponse = DeleteMcpServersByServerSlugCredentialsResponses[keyof DeleteMcpServersByServerSlugCredentialsResponses];

export type GetMcpServersByServerSlugCredentialsData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: {
        /**
         * If "true", retrieves credentials for all users (only available for admins).
         */
        all?: string;
    };
    url: '/mcp-servers/{serverSlug}/credentials';
};

export type GetMcpServersByServerSlugCredentialsResponses = {
    /**
     * Successful response
     */
    200: {
        credentials: Array<ServerCredentialsDto>;
    };
};

export type GetMcpServersByServerSlugCredentialsResponse = GetMcpServersByServerSlugCredentialsResponses[keyof GetMcpServersByServerSlugCredentialsResponses];

export type DeleteMcpServersByServerSlugCredentialsByCredentialsIdData = {
    body?: never;
    path: {
        serverSlug: string;
        credentialsId: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/credentials/{credentialsId}';
};

export type DeleteMcpServersByServerSlugCredentialsByCredentialsIdResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type GetMcpServersByServerSlugSourceCodeData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/source-code';
};

export type GetMcpServersByServerSlugSourceCodeResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type PutMcpServersByServerSlugSourceCodeData = {
    body?: {
        file: unknown;
    };
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/source-code';
};

export type PutMcpServersByServerSlugSourceCodeResponses = {
    /**
     * Successful response
     */
    200: UploadSourceCodeResponse;
};

export type PutMcpServersByServerSlugSourceCodeResponse = PutMcpServersByServerSlugSourceCodeResponses[keyof PutMcpServersByServerSlugSourceCodeResponses];

export type GetMcpServersByServerSlugFilesData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/files';
};

export type GetMcpServersByServerSlugFilesResponses = {
    /**
     * Successful response
     */
    200: {
        files: Array<ServerFile>;
    };
};

export type GetMcpServersByServerSlugFilesResponse = GetMcpServersByServerSlugFilesResponses[keyof GetMcpServersByServerSlugFilesResponses];

export type PostMcpServersByServerSlugFilesData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/files';
};

export type PostMcpServersByServerSlugFilesResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
    };
};

export type PostMcpServersByServerSlugFilesResponse = PostMcpServersByServerSlugFilesResponses[keyof PostMcpServersByServerSlugFilesResponses];

export type PutMcpServersByServerSlugFilesByFileIdNameData = {
    body?: {
        filename: string;
    };
    path: {
        serverSlug: string;
        fileId: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/files/{fileId}/name';
};

export type PutMcpServersByServerSlugFilesByFileIdNameResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PutMcpServersByServerSlugFilesByFileIdNameResponse = PutMcpServersByServerSlugFilesByFileIdNameResponses[keyof PutMcpServersByServerSlugFilesByFileIdNameResponses];

export type DeleteMcpServersByServerSlugFilesByFileIdData = {
    body?: never;
    path: {
        serverSlug: string;
        fileId: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/files/{fileId}';
};

export type DeleteMcpServersByServerSlugFilesByFileIdResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type GetMcpServersByServerSlugFilesByFileIdData = {
    body?: never;
    path: {
        serverSlug: string;
        fileId: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/files/{fileId}';
};

export type GetMcpServersByServerSlugFilesByFileIdResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type PutMcpServersByServerSlugFilesByFileIdData = {
    body?: never;
    path: {
        serverSlug: string;
        fileId: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/files/{fileId}';
};

export type PutMcpServersByServerSlugFilesByFileIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PutMcpServersByServerSlugFilesByFileIdResponse = PutMcpServersByServerSlugFilesByFileIdResponses[keyof PutMcpServersByServerSlugFilesByFileIdResponses];

export type GetTenantsByTenantIdData = {
    body?: never;
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/tenants/{tenantId}';
};

export type GetTenantsByTenantIdResponses = {
    /**
     * Successful response
     */
    200: {
        tenant: TenantDto;
    };
};

export type GetTenantsByTenantIdResponse = GetTenantsByTenantIdResponses[keyof GetTenantsByTenantIdResponses];

export type GetTenantsByTenantIdSubscriptionData = {
    body?: never;
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/tenants/{tenantId}/subscription';
};

export type GetTenantsByTenantIdSubscriptionResponses = {
    /**
     * Successful response
     */
    200: GetSubscriptionResponse;
};

export type GetTenantsByTenantIdSubscriptionResponse = GetTenantsByTenantIdSubscriptionResponses[keyof GetTenantsByTenantIdSubscriptionResponses];

export type GetTeamsData = {
    body?: never;
    path?: never;
    query?: {
        userSub?: string;
    };
    url: '/teams';
};

export type GetTeamsResponses = {
    /**
     * Successful response
     */
    200: {
        teams: Array<TeamWithMemberCount>;
    };
};

export type GetTeamsResponse = GetTeamsResponses[keyof GetTeamsResponses];

export type PostTeamsData = {
    body?: {
        name: string;
        description: string;
    };
    path?: never;
    query?: never;
    url: '/teams';
};

export type PostTeamsResponses = {
    /**
     * Successful response
     */
    200: {
        team: TeamWithMemberCount;
    };
};

export type PostTeamsResponse = PostTeamsResponses[keyof PostTeamsResponses];

export type DeleteTeamsByTeamIdData = {
    body?: never;
    path: {
        teamId: string;
    };
    query?: never;
    url: '/teams/{teamId}';
};

export type DeleteTeamsByTeamIdResponses = {
    /**
     * Successful response
     */
    200: {
        [key: string]: never;
    };
};

export type DeleteTeamsByTeamIdResponse = DeleteTeamsByTeamIdResponses[keyof DeleteTeamsByTeamIdResponses];

export type GetTeamsByTeamIdData = {
    body?: never;
    path: {
        teamId: string;
    };
    query?: never;
    url: '/teams/{teamId}';
};

export type GetTeamsByTeamIdResponses = {
    /**
     * Successful response
     */
    200: {
        team: TeamWithMemberCount;
    };
};

export type GetTeamsByTeamIdResponse = GetTeamsByTeamIdResponses[keyof GetTeamsByTeamIdResponses];

export type PutTeamsByTeamIdData = {
    body?: {
        name: string;
        description: string;
    };
    path: {
        teamId: string;
    };
    query?: never;
    url: '/teams/{teamId}';
};

export type PutTeamsByTeamIdResponses = {
    /**
     * Successful response
     */
    200: {
        team: TeamWithMemberCount;
    };
};

export type PutTeamsByTeamIdResponse = PutTeamsByTeamIdResponses[keyof PutTeamsByTeamIdResponses];

export type GetTeamsByTeamIdMembersData = {
    body?: never;
    path: {
        teamId: string;
    };
    query?: never;
    url: '/teams/{teamId}/members';
};

export type GetTeamsByTeamIdMembersResponses = {
    /**
     * Successful response
     */
    200: {
        members: Array<{
            member: TeamMember;
            user: User;
        }>;
    };
};

export type GetTeamsByTeamIdMembersResponse = GetTeamsByTeamIdMembersResponses[keyof GetTeamsByTeamIdMembersResponses];

export type PostTeamsByTeamIdMembersData = {
    body?: {
        userId: string;
        role: 'member' | 'maintainer';
    };
    path: {
        teamId: string;
    };
    query?: never;
    url: '/teams/{teamId}/members';
};

export type PostTeamsByTeamIdMembersResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PostTeamsByTeamIdMembersResponse = PostTeamsByTeamIdMembersResponses[keyof PostTeamsByTeamIdMembersResponses];

export type DeleteTeamsByTeamIdMembersByUserIdData = {
    body?: never;
    path: {
        teamId: string;
        userId: string;
    };
    query?: never;
    url: '/teams/{teamId}/members/{userId}';
};

export type DeleteTeamsByTeamIdMembersByUserIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type DeleteTeamsByTeamIdMembersByUserIdResponse = DeleteTeamsByTeamIdMembersByUserIdResponses[keyof DeleteTeamsByTeamIdMembersByUserIdResponses];

export type PutTeamsByTeamIdMembersByUserIdData = {
    body?: {
        role: 'member' | 'maintainer';
    };
    path: {
        teamId: string;
        userId: string;
    };
    query?: never;
    url: '/teams/{teamId}/members/{userId}';
};

export type PutTeamsByTeamIdMembersByUserIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PutTeamsByTeamIdMembersByUserIdResponse = PutTeamsByTeamIdMembersByUserIdResponses[keyof PutTeamsByTeamIdMembersByUserIdResponses];

export type GetTeamsByTeamIdInvitationsData = {
    body?: never;
    path: {
        teamId: string;
    };
    query?: never;
    url: '/teams/{teamId}/invitations';
};

export type GetTeamsByTeamIdInvitationsResponses = {
    /**
     * Successful response
     */
    200: {
        invitations: Array<TeamInvitation>;
    };
};

export type GetTeamsByTeamIdInvitationsResponse = GetTeamsByTeamIdInvitationsResponses[keyof GetTeamsByTeamIdInvitationsResponses];

export type PostTeamsByTeamIdInvitationsData = {
    body?: {
        email: string;
        role: 'member' | 'maintainer';
    };
    path: {
        teamId: string;
    };
    query?: never;
    url: '/teams/{teamId}/invitations';
};

export type PostTeamsByTeamIdInvitationsResponses = {
    /**
     * Successful response
     */
    200: {
        invitation: TeamInvitation;
    };
};

export type PostTeamsByTeamIdInvitationsResponse = PostTeamsByTeamIdInvitationsResponses[keyof PostTeamsByTeamIdInvitationsResponses];

export type DeleteTeamsByTeamIdInvitationsByInvitationIdData = {
    body?: never;
    path: {
        teamId: string;
        invitationId: string;
    };
    query?: never;
    url: '/teams/{teamId}/invitations/{invitationId}';
};

export type DeleteTeamsByTeamIdInvitationsByInvitationIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type DeleteTeamsByTeamIdInvitationsByInvitationIdResponse = DeleteTeamsByTeamIdInvitationsByInvitationIdResponses[keyof DeleteTeamsByTeamIdInvitationsByInvitationIdResponses];

export type GetTeamsByTeamIdServersData = {
    body?: never;
    path: {
        teamId: string;
    };
    query?: never;
    url: '/teams/{teamId}/servers';
};

export type GetTeamsByTeamIdServersResponses = {
    /**
     * Successful response
     */
    200: {
        permissions: Array<{
            permission: ServerMember;
            server: Server;
        }>;
    };
};

export type GetTeamsByTeamIdServersResponse = GetTeamsByTeamIdServersResponses[keyof GetTeamsByTeamIdServersResponses];

export type GetTeamsByTeamIdClaimMappingsData = {
    body?: never;
    path: {
        teamId: string;
    };
    query?: never;
    url: '/teams/{teamId}/claim-mappings';
};

export type GetTeamsByTeamIdClaimMappingsResponses = {
    /**
     * Successful response
     */
    200: {
        claimMappings: Array<TeamClaimMapping>;
    };
};

export type GetTeamsByTeamIdClaimMappingsResponse = GetTeamsByTeamIdClaimMappingsResponses[keyof GetTeamsByTeamIdClaimMappingsResponses];

export type PostTeamsByTeamIdClaimMappingsData = {
    body?: {
        claimKey: string;
        claimValue: string;
    };
    path: {
        teamId: string;
    };
    query?: never;
    url: '/teams/{teamId}/claim-mappings';
};

export type PostTeamsByTeamIdClaimMappingsResponses = {
    /**
     * Successful response
     */
    200: {
        claimMapping: TeamClaimMapping;
    };
};

export type PostTeamsByTeamIdClaimMappingsResponse = PostTeamsByTeamIdClaimMappingsResponses[keyof PostTeamsByTeamIdClaimMappingsResponses];

export type DeleteTeamsByTeamIdClaimMappingsByMappingIdData = {
    body?: never;
    path: {
        teamId: string;
        mappingId: string;
    };
    query?: never;
    url: '/teams/{teamId}/claim-mappings/{mappingId}';
};

export type DeleteTeamsByTeamIdClaimMappingsByMappingIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type DeleteTeamsByTeamIdClaimMappingsByMappingIdResponse = DeleteTeamsByTeamIdClaimMappingsByMappingIdResponses[keyof DeleteTeamsByTeamIdClaimMappingsByMappingIdResponses];

export type GetSecretStoresData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/secret-stores';
};

export type GetSecretStoresResponses = {
    /**
     * Successful response
     */
    200: SecretStoreListResponse;
};

export type GetSecretStoresResponse = GetSecretStoresResponses[keyof GetSecretStoresResponses];

export type PostSecretStoresData = {
    body?: {
        name: string;
        type: 'aws_secrets_manager' | 'gcp_secret_manager' | 'hashicorp_vault' | 'infisical' | 'azure_key_vault';
        configuration: AwsSecretsManagerConfiguration | GcpSecretManagerConfiguration | HashiCorpVaultConfiguration | InfisicalConfiguration | AzureKeyVaultConfiguration;
    };
    path?: never;
    query?: never;
    url: '/secret-stores';
};

export type PostSecretStoresResponses = {
    /**
     * Successful response
     */
    200: SecretStoreResponse;
};

export type PostSecretStoresResponse = PostSecretStoresResponses[keyof PostSecretStoresResponses];

export type DeleteSecretStoresByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/secret-stores/{id}';
};

export type DeleteSecretStoresByIdResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type GetSecretStoresByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/secret-stores/{id}';
};

export type GetSecretStoresByIdResponses = {
    /**
     * Successful response
     */
    200: SecretStoreDetailResponse;
};

export type GetSecretStoresByIdResponse = GetSecretStoresByIdResponses[keyof GetSecretStoresByIdResponses];

export type PatchSecretStoresByIdData = {
    body?: {
        name?: string;
        configuration?: AwsSecretsManagerConfiguration | GcpSecretManagerConfiguration | HashiCorpVaultConfiguration | InfisicalConfiguration | AzureKeyVaultConfiguration;
        isEnabled?: boolean;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/secret-stores/{id}';
};

export type PatchSecretStoresByIdResponses = {
    /**
     * Successful response
     */
    200: SecretStoreResponse;
};

export type PatchSecretStoresByIdResponse = PatchSecretStoresByIdResponses[keyof PatchSecretStoresByIdResponses];

export type GetSecretStoresByStoreIdMappingsData = {
    body?: never;
    path: {
        storeId: string;
    };
    query?: never;
    url: '/secret-stores/{storeId}/mappings';
};

export type GetSecretStoresByStoreIdMappingsResponses = {
    /**
     * Successful response
     */
    200: SecretMappingListResponse;
};

export type GetSecretStoresByStoreIdMappingsResponse = GetSecretStoresByStoreIdMappingsResponses[keyof GetSecretStoresByStoreIdMappingsResponses];

export type PostSecretStoresByStoreIdMappingsData = {
    body?: {
        name: string;
        secretIdentifier: string;
    };
    path: {
        storeId: string;
    };
    query?: never;
    url: '/secret-stores/{storeId}/mappings';
};

export type PostSecretStoresByStoreIdMappingsResponses = {
    /**
     * Successful response
     */
    200: SecretMappingResponse;
};

export type PostSecretStoresByStoreIdMappingsResponse = PostSecretStoresByStoreIdMappingsResponses[keyof PostSecretStoresByStoreIdMappingsResponses];

export type DeleteSecretStoresByStoreIdMappingsByMappingNameData = {
    body?: never;
    path: {
        storeId: string;
        mappingName: string;
    };
    query?: never;
    url: '/secret-stores/{storeId}/mappings/{mappingName}';
};

export type DeleteSecretStoresByStoreIdMappingsByMappingNameResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type PatchSecretStoresByStoreIdMappingsByMappingNameData = {
    body?: {
        name?: string;
        secretIdentifier?: string;
    };
    path: {
        storeId: string;
        mappingName: string;
    };
    query?: never;
    url: '/secret-stores/{storeId}/mappings/{mappingName}';
};

export type PatchSecretStoresByStoreIdMappingsByMappingNameResponses = {
    /**
     * Successful response
     */
    200: SecretMappingResponse;
};

export type PatchSecretStoresByStoreIdMappingsByMappingNameResponse = PatchSecretStoresByStoreIdMappingsByMappingNameResponses[keyof PatchSecretStoresByStoreIdMappingsByMappingNameResponses];

export type PostSecretStoresByStoreIdTestData = {
    body?: TestSecretRequest;
    path: {
        storeId: string;
    };
    query?: never;
    url: '/secret-stores/{storeId}/test';
};

export type PostSecretStoresByStoreIdTestResponses = {
    /**
     * Successful response
     */
    200: TestSecretResponse;
};

export type PostSecretStoresByStoreIdTestResponse = PostSecretStoresByStoreIdTestResponses[keyof PostSecretStoresByStoreIdTestResponses];

export type GetProfilesData = {
    body?: never;
    path?: never;
    query?: {
        serverSlug?: string;
    };
    url: '/profiles';
};

export type GetProfilesResponses = {
    /**
     * Successful response
     */
    200: {
        profiles: Array<Profile>;
    };
};

export type GetProfilesResponse = GetProfilesResponses[keyof GetProfilesResponses];

export type PostProfilesData = {
    body?: {
        name: string;
        description: string;
        isOpenToAllUsers: boolean;
        isRestrictive: boolean;
    };
    path?: never;
    query?: never;
    url: '/profiles';
};

export type PostProfilesResponses = {
    /**
     * Successful response
     */
    200: {
        profile: ProfileDetailsDto;
    };
};

export type PostProfilesResponse = PostProfilesResponses[keyof PostProfilesResponses];

export type DeleteProfilesByProfileIdData = {
    body?: never;
    path: {
        profileId: string;
    };
    query?: never;
    url: '/profiles/{profileId}';
};

export type DeleteProfilesByProfileIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type DeleteProfilesByProfileIdResponse = DeleteProfilesByProfileIdResponses[keyof DeleteProfilesByProfileIdResponses];

export type GetProfilesByProfileIdData = {
    body?: never;
    path: {
        profileId: string;
    };
    query?: never;
    url: '/profiles/{profileId}';
};

export type GetProfilesByProfileIdResponses = {
    /**
     * Successful response
     */
    200: {
        profile: ProfileDetailsDto;
    };
};

export type GetProfilesByProfileIdResponse = GetProfilesByProfileIdResponses[keyof GetProfilesByProfileIdResponses];

export type PutProfilesByProfileIdData = {
    body?: {
        name?: string;
        description?: string;
        isOpenToAllUsers?: boolean;
        isRestrictive?: boolean;
        serverIds?: Array<string>;
    };
    path: {
        profileId: string;
    };
    query?: never;
    url: '/profiles/{profileId}';
};

export type PutProfilesByProfileIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PutProfilesByProfileIdResponse = PutProfilesByProfileIdResponses[keyof PutProfilesByProfileIdResponses];

export type GetProfilesByProfileIdClaimMappingsData = {
    body?: never;
    path: {
        profileId: string;
    };
    query?: never;
    url: '/profiles/{profileId}/claim-mappings';
};

export type GetProfilesByProfileIdClaimMappingsResponses = {
    /**
     * Successful response
     */
    200: {
        claimMappings: Array<ProfileClaimMapping>;
    };
};

export type GetProfilesByProfileIdClaimMappingsResponse = GetProfilesByProfileIdClaimMappingsResponses[keyof GetProfilesByProfileIdClaimMappingsResponses];

export type PostProfilesByProfileIdClaimMappingsData = {
    body?: {
        claimKey: string;
        claimValue: string;
    };
    path: {
        profileId: string;
    };
    query?: never;
    url: '/profiles/{profileId}/claim-mappings';
};

export type PostProfilesByProfileIdClaimMappingsResponses = {
    /**
     * Successful response
     */
    200: {
        claimMapping: ProfileClaimMapping;
    };
};

export type PostProfilesByProfileIdClaimMappingsResponse = PostProfilesByProfileIdClaimMappingsResponses[keyof PostProfilesByProfileIdClaimMappingsResponses];

export type DeleteProfilesByProfileIdClaimMappingsByMappingIdData = {
    body?: never;
    path: {
        profileId: string;
        mappingId: string;
    };
    query?: never;
    url: '/profiles/{profileId}/claim-mappings/{mappingId}';
};

export type DeleteProfilesByProfileIdClaimMappingsByMappingIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type DeleteProfilesByProfileIdClaimMappingsByMappingIdResponse = DeleteProfilesByProfileIdClaimMappingsByMappingIdResponses[keyof DeleteProfilesByProfileIdClaimMappingsByMappingIdResponses];

export type GetProfilesByProfileIdToolsData = {
    body?: never;
    path: {
        profileId: string;
    };
    query?: never;
    url: '/profiles/{profileId}/tools';
};

export type GetProfilesByProfileIdToolsResponses = {
    /**
     * Successful response
     */
    200: {
        tools: {
            [key: string]: Array<string>;
        };
    };
};

export type GetProfilesByProfileIdToolsResponse = GetProfilesByProfileIdToolsResponses[keyof GetProfilesByProfileIdToolsResponses];

export type PutProfilesByProfileIdServersByServerSlugToolsData = {
    body?: {
        toolNames: Array<string>;
    };
    path: {
        profileId: string;
        serverSlug: string;
    };
    query?: never;
    url: '/profiles/{profileId}/servers/{serverSlug}/tools';
};

export type PutProfilesByProfileIdServersByServerSlugToolsResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PutProfilesByProfileIdServersByServerSlugToolsResponse = PutProfilesByProfileIdServersByServerSlugToolsResponses[keyof PutProfilesByProfileIdServersByServerSlugToolsResponses];

export type ClientOptions = {
    baseUrl: 'https://{YOUR_ORG_ID}.gatana.ai/api/v1' | (string & {});
};