// This file is auto-generated by @hey-api/openapi-ts

export type CreateUserRequest = {
    email: string;
    name: string;
    role: 'member' | 'owner';
    isServiceAccount: boolean;
};

export type UpdateUserRequest = {
    email: string;
    name: string;
    role: 'member' | 'owner';
    isDisabled: boolean;
};

export type CreateMcpServerRequest = {
    name: string;
    slug: string;
    description?: string;
    logoUrl?: string;
    /**
     * The URL of the remote MCP server
     */
    url?: string;
    authorization: {
        method: 'none' | 'oauth' | 'apikey';
    };
    transportType: 'self' | 'hosted' | 'stdio' | 'httpstreaming' | 'sse';
    transportConfig: HttpStreamingTransportConfig | HostedTransportConfig | StdioTransportConfig | SseTransportConfig;
};

export type HttpStreamingTransportConfig = {
    type: 'httpstreaming';
    url: string;
    headers?: Array<[
        string,
        string
    ]>;
};

export type HostedTransportConfig = {
    type: 'hosted';
    runtime: 'node24';
    env?: Array<[
        string,
        string
    ]>;
};

export type StdioTransportConfig = {
    type: 'stdio';
    command: string;
    dockerImage?: string;
    env?: Array<[
        string,
        string
    ]>;
};

export type SseTransportConfig = {
    type: 'sse';
    url: string;
    headers?: Array<[
        string,
        string
    ]>;
};

export type UpdateMcpServerRequest = {
    name: string;
    slug: string;
    description?: string;
    logoUrl?: string;
    /**
     * The URL of the remote MCP server
     */
    url?: string;
    authorization: {
        method: 'none' | 'oauth' | 'apikey';
    };
    transportConfig: HttpStreamingTransportConfig | HostedTransportConfig | StdioTransportConfig | SseTransportConfig;
};

export type UpdateTenantRequest = {
    displayName?: string;
    upstreamOidcConfiguration?: {
        isEnabled: boolean;
        displayName: string;
        issuer: string;
        clientId: string;
        clientSecret: string;
        clientAuthMethod: 'client_secret_basic' | 'client_secret_post';
        scopes: string;
    } | null;
    upstreamSamlConfiguration?: {
        isEnabled: boolean;
        displayName: string;
        idpMetadataUrl?: string;
        idpMetadataDocument: string;
        entryPoint: string;
        cert: string;
        identifierFormat: string;
        signatureAlgorithm: string;
        emailClaim: string;
        firstNameClaim: string;
        lastNameClaim: string;
    } | null;
    isMcpAuthorizationApiKeyEnabled?: boolean;
    grantPermissionsNewToolPolicy?: boolean;
    allowMemberAddRemoteServers?: boolean;
    allowMemberAddLocalServers?: boolean;
    allowMemberAddHostedServers?: boolean;
    memberDefaultRole?: ('member' | 'admin' | 'maintainer') | 'none';
};

export type TriggerWebhookConfiguration = {
    requiredHeaders?: Array<[
        string,
        string
    ]>;
};

export type TriggerScheduledConfiguration = {
    cron: string;
    timezone: string;
};

export type PurchaseCreditsRequest = {
    /**
     * The amount of credits to purchase (1 credit = $1)
     */
    amount: number;
};

export type AuthMetadata = {
    isPlayground: boolean;
    serversGranted: Array<{
        id: number;
        name: string;
        isEnabled: boolean;
        transportType: string;
        usageCount: number;
        slug: string;
    }>;
    user: {
        id: number;
        sub: string;
        tenantId: string;
        name: string;
        apiKey: string;
        email: string;
        role: 'member' | 'owner';
        isServiceAccount: boolean;
        createdAt: string;
        updatedAt: string;
        isSuperAdministrator?: boolean;
    };
    tenant: {
        id: string;
        isMcpAuthorizationApiKeyEnabled: boolean;
        grantUsersInstallServersPolicy: boolean;
        displayName: string;
        isTrial: boolean;
        subscriptionPlan: string;
        subscriptionSeats: number;
        numberOfEnabledUsers?: number;
        freeCredits: number;
        paidCredits: number;
    };
    rules: Array<unknown>;
};

export type AuditLog = {
    readonly id: number;
    tenantId: string;
    eventTime: string;
    entityType: string | null;
    entityId: number | null;
    eventName: string;
    userId: number | null;
    details: unknown;
    onlySuperadminVisibility: boolean;
    createdAt: string;
};

export type PaginatedAuditLogs = {
    data: Array<AuditLogResponse>;
    pagination: {
        page: number;
        limit: number;
        total: number;
        totalPages: number;
        hasNext: boolean;
        hasPrev: boolean;
    };
};

export type AuditLogResponse = {
    readonly id: number;
    tenantId: string;
    eventTime: string;
    entityType: string | null;
    entityId: number | null;
    eventName: string;
    userId: number | null;
    details: unknown;
    onlySuperadminVisibility: boolean;
    createdAt: string;
    userEmail: string | null;
    userSub: string | null;
    teamName: string | null;
    serverSlug: string | null;
};

export type UserIdentity = {
    tenantId: number;
    externalId: string;
    userId: number;
    type: 'external-oidc' | 'external-saml' | 'native';
    createdAt: string;
    updatedAt: string;
};

export type User = {
    id: number;
    sub: string;
    tenantId: string;
    name: string;
    email: string;
    role: 'member' | 'owner';
    isSuperAdministrator: boolean;
    isDisabled: boolean;
    isServiceAccount: boolean;
    apiKey: string;
    createdAt: string;
    updatedAt: string;
};

export type TenantMcpServer = {
    id: number;
    slug: string;
    tenantId: string;
    name: string;
    description: string;
    logoUrl?: string;
    authorization: {
        method: 'none' | 'oauth' | 'apikey';
    };
    transportType: 'self' | 'hosted' | 'stdio' | 'httpstreaming' | 'sse';
    transportConfig: HttpStreamingTransportConfigOutput | StdioTransportConfigOutput | SseTransportConfigOutput | {
        type: 'self';
        id: string;
    } | HostedTransportConfigOutput;
    oauthClientConfiguration: null | {
        clientId: string;
        clientSecret: string;
        clientAuthMethod: 'client_secret_basic' | 'client_secret_post' | 'none' | string;
        scopes: string;
        tokenSet?: {
            accessToken: string;
            accessTokenExpiresAt?: number;
            idToken?: string;
            refreshToken?: string;
        };
    };
    oauthMetadata: null | {
        requiresAuthorization: boolean;
        resource?: {
            id: string;
            availableScopes: Array<string>;
            metadataUrl: string;
        };
        as?: {
            issuer: string;
            authorizeEndpoint: string;
            tokenEndpoint: string;
            registrationEndpoint?: string;
            supportsPKCE: boolean;
            supportedClientAuthMethods: Array<string>;
            supportsDynamicClientRegistration: boolean;
            noDynamicClientRegistrationReason?: string | null;
            serviceDocumentation: string;
            metadataUrl: string;
        };
    };
    isEnabled: boolean;
    createdAt: string;
    updatedAt: string;
};

export type ServerFile = {
    tenantId: string;
    serverId: string;
    id: string;
    filename: string;
    sourceType: 'gcs' | 'aws-ssm' | 'aws-secrets-manager';
    sourceId: string;
    size: number | null;
    credentialId: string | null;
    createdAt: string;
    updatedAt: string;
};

export type McpServerRunningStatusResponse = {
    isDeployed: boolean;
    isAvailable: boolean;
    isStabilizing: boolean;
    pods: Array<McpServerPodStatus>;
};

export type McpServerPodStatus = {
    name: string;
    ready: boolean;
    phase?: string;
    reason?: string;
    createdAt?: string;
};

export type McpServerTool = {
    tenantId: string;
    serverId: number;
    toolName: string;
    description: string;
    schema: {
        [key: string]: never;
    };
    isEnabled: boolean;
    createdAt: number;
    updatedAt: number;
};

export type GetMembersResponse = {
    teams: Array<{
        role: 'member' | 'admin' | 'maintainer';
        id: string;
        name: string;
    }>;
    users: Array<{
        role: 'member' | 'admin' | 'maintainer';
        sub: string;
        name: string;
        email: string;
    }>;
};

export type UploadSourceCodeResponse = {
    success: boolean;
    message: string;
    analysisResult?: unknown;
};

export type Tenant = {
    id: string;
    displayName: string;
    rootEmail: string | null;
    isDisabled: boolean;
    isMcpAuthorizationApiKeyEnabled: boolean;
    mcpAuthorizationApiKey: string;
    grantPermissionsNewToolPolicy: boolean;
    stripeCustomerId: string;
    stripeSubscriptionId: string;
    subscriptionPlan: string;
    stripeCachedSubscription: unknown | null;
    subscriptionSeats: number;
    isPlayground: boolean;
    freeCredits: number;
    paidCredits: number;
    upstreamOidcConfiguration: {
        isEnabled: boolean;
        displayName: string;
        issuer: string;
        clientId: string;
        clientSecret: string;
        clientAuthMethod: 'client_secret_basic' | 'client_secret_post';
        scopes: string;
    } | null;
    upstreamSamlConfiguration: {
        isEnabled: boolean;
        displayName: string;
        idpMetadataUrl: string;
        idpMetadataDocument: string;
        entryPoint: string;
        cert: string;
        identifierFormat: string;
        signatureAlgorithm: string;
        emailClaim: string;
        firstNameClaim: string;
        lastNameClaim: string;
    } | null;
    allowMemberAddRemoteServers: boolean;
    allowMemberAddLocalServers: boolean;
    allowMemberAddHostedServers: boolean;
    memberDefaultRole: ('member' | 'admin' | 'maintainer') | 'none';
    createdAt: string;
    updatedAt: string;
};

export type LlmApi = {
    id: string;
    name: string;
    createdAt: string;
    updatedAt: string;
};

export type LlmModel = {
    id: string;
    name: string;
    llmApiId: 'googleai' | 'openai' | 'xai';
    supportedContextFiles: Array<{
        name: string;
        maxCount: number;
        maxSize: number;
        mime: Array<string>;
    }>;
    supportsChat: boolean;
    tokenInputCostPerMillion: number;
    tokenOutputCostPerMillion: number;
    isEnabled: boolean;
    createdAt: string;
    updatedAt: string;
};

export type Agent = {
    id: string;
    tenantId: string;
    modelId: string;
    llmApiId: string;
    apiKeyId: string | null;
    name: string;
    description: string;
    modelConfiguration: {
        [key: string]: unknown;
    };
    systemMessage: string;
    inputSchema: string;
    outputSchema: string;
    prompt: string;
    isEnabled: boolean;
    createdAt: string;
    updatedAt: string;
};

export type TenantLlmKey = {
    id: string;
    tenantId: string;
    llmApiId: string;
    name: string;
    key: string;
    isEnabled: boolean;
    extra: {
        [key: string]: unknown;
    };
    createdAt: string;
    updatedAt: string;
};

export type AgentContextFile = {
    id: string;
    tenantId: string;
    agentId: string;
    name: string;
    size: number;
    mime: string;
    isEnabled: boolean;
    createdAt: string;
    updatedAt: string;
};

export type AgentRun = {
    id: string;
    tenantId: string;
    agentId: string;
    input: unknown;
    output: {
        type: 'error';
        data: string;
    } | {
        type: 'genkit';
        data: {
            message?: {
                role: 'system' | 'user' | 'model' | 'tool';
                content: Array<{
                    text: string;
                    media?: unknown;
                    toolRequest?: unknown;
                    toolResponse?: unknown;
                    data?: unknown;
                    metadata?: {
                        [key: string]: unknown;
                    };
                    custom?: {
                        [key: string]: unknown;
                    };
                    reasoning?: unknown;
                    resource?: unknown;
                } | {
                    text?: unknown;
                    media: {
                        contentType?: string;
                        url: string;
                    };
                    toolRequest?: unknown;
                    toolResponse?: unknown;
                    data?: unknown;
                    metadata?: {
                        [key: string]: unknown;
                    };
                    custom?: {
                        [key: string]: unknown;
                    };
                    reasoning?: unknown;
                    resource?: unknown;
                }>;
                metadata?: {
                    [key: string]: unknown;
                };
            };
            finishReason?: 'stop' | 'length' | 'blocked' | 'interrupted' | 'other' | 'unknown';
            finishMessage?: string;
            latencyMs?: number;
            usage?: {
                inputTokens?: number;
                outputTokens?: number;
                totalTokens?: number;
                inputCharacters?: number;
                outputCharacters?: number;
                inputImages?: number;
                outputImages?: number;
                inputVideos?: number;
                outputVideos?: number;
                inputAudioFiles?: number;
                outputAudioFiles?: number;
                custom?: {
                    [key: string]: number;
                };
                thoughtsTokens?: number;
                cachedContentTokens?: number;
            };
            custom: unknown;
            raw: unknown;
            request?: {
                messages: Array<{
                    role: 'system' | 'user' | 'model' | 'tool';
                    content: Array<{
                        text: string;
                        media?: unknown;
                        toolRequest?: unknown;
                        toolResponse?: unknown;
                        data?: unknown;
                        metadata?: {
                            [key: string]: unknown;
                        };
                        custom?: {
                            [key: string]: unknown;
                        };
                        reasoning?: unknown;
                        resource?: unknown;
                    } | {
                        text?: unknown;
                        media: {
                            contentType?: string;
                            url: string;
                        };
                        toolRequest?: unknown;
                        toolResponse?: unknown;
                        data?: unknown;
                        metadata?: {
                            [key: string]: unknown;
                        };
                        custom?: {
                            [key: string]: unknown;
                        };
                        reasoning?: unknown;
                        resource?: unknown;
                    }>;
                    metadata?: {
                        [key: string]: unknown;
                    };
                }>;
                config?: unknown;
                tools?: Array<{
                    name: string;
                    description: string;
                    inputSchema?: {
                        [key: string]: unknown;
                    } | null;
                    outputSchema?: {
                        [key: string]: unknown;
                    } | null;
                    /**
                     * additional metadata for this tool definition
                     */
                    metadata?: {
                        [key: string]: unknown;
                    };
                }>;
                toolChoice?: 'auto' | 'required' | 'none';
                output?: {
                    format?: string;
                    schema?: {
                        [key: string]: unknown;
                    };
                    constrained?: boolean;
                    contentType?: string;
                };
                docs?: Array<{
                    content: Array<{
                        text: string;
                        media?: unknown;
                        toolRequest?: unknown;
                        toolResponse?: unknown;
                        data?: unknown;
                        metadata?: {
                            [key: string]: unknown;
                        };
                        custom?: {
                            [key: string]: unknown;
                        };
                        reasoning?: unknown;
                        resource?: unknown;
                    } | {
                        text?: unknown;
                        media: {
                            contentType?: string;
                            url: string;
                        };
                        toolRequest?: unknown;
                        toolResponse?: unknown;
                        data?: unknown;
                        metadata?: {
                            [key: string]: unknown;
                        };
                        custom?: {
                            [key: string]: unknown;
                        };
                        reasoning?: unknown;
                        resource?: unknown;
                    }>;
                    metadata?: {
                        [key: string]: unknown;
                    };
                }>;
                candidates?: number;
            };
            operation?: {
                action?: string;
                id: string;
                done?: boolean;
                output?: unknown;
                error?: {
                    message: string;
                    [key: string]: unknown | string;
                };
                metadata?: {
                    [key: string]: unknown;
                };
            };
            candidates?: Array<{
                index: number;
                message: {
                    role: 'system' | 'user' | 'model' | 'tool';
                    content: Array<{
                        text: string;
                        media?: unknown;
                        toolRequest?: unknown;
                        toolResponse?: unknown;
                        data?: unknown;
                        metadata?: {
                            [key: string]: unknown;
                        };
                        custom?: {
                            [key: string]: unknown;
                        };
                        reasoning?: unknown;
                        resource?: unknown;
                    } | {
                        text?: unknown;
                        media: {
                            contentType?: string;
                            url: string;
                        };
                        toolRequest?: unknown;
                        toolResponse?: unknown;
                        data?: unknown;
                        metadata?: {
                            [key: string]: unknown;
                        };
                        custom?: {
                            [key: string]: unknown;
                        };
                        reasoning?: unknown;
                        resource?: unknown;
                    }>;
                    metadata?: {
                        [key: string]: unknown;
                    };
                };
                usage?: {
                    inputTokens?: number;
                    outputTokens?: number;
                    totalTokens?: number;
                    inputCharacters?: number;
                    outputCharacters?: number;
                    inputImages?: number;
                    outputImages?: number;
                    inputVideos?: number;
                    outputVideos?: number;
                    inputAudioFiles?: number;
                    outputAudioFiles?: number;
                    custom?: {
                        [key: string]: number;
                    };
                    thoughtsTokens?: number;
                    cachedContentTokens?: number;
                };
                finishReason: 'stop' | 'length' | 'blocked' | 'interrupted' | 'other' | 'unknown';
                finishMessage?: string;
                custom: unknown;
            }>;
        };
    };
    outcome: 'unknown' | 'success' | 'failure';
    createdAt: string;
    updatedAt: string;
};

export type TenantUsage = {
    id: number;
    tenantId: string | null;
    type: 'AgentRun' | 'FreeCredit' | 'PaidCredit' | 'McpToolCall';
    amount: number;
    meta: {
        [key: string]: unknown;
    };
    createdAt: string;
    updatedAt: string;
};

export type AgentRunToolCall = {
    id: string;
    tenantId: string;
    agentId: string;
    toolName: string;
    input: {
        [key: string]: unknown;
    };
    output: {
        [key: string]: unknown;
    } | null;
    outcome: 'success' | 'failure' | 'unknown';
    createdAt: string;
    updatedAt: string;
};

export type Trigger = {
    id: string;
    tenantId: string;
    name: string;
    type: 'webhook' | 'scheduled';
    configuration: TriggerWebhookConfigurationOutput | TriggerScheduledConfigurationOutput;
    isEnabled: boolean;
    createdAt: string;
    updatedAt: string;
};

export type TriggerTarget = {
    lastInvoked: string | null;
    agent: Agent;
};

export type TriggerInvocation = {
    id: string;
    tenantId: string;
    triggerId: string;
    agentId: string;
    runId: string | null;
    outcome: 'skipped' | 'invoked';
    meta: {
        [key: string]: unknown;
    };
    createdAt: string;
    updatedAt: string;
};

export type UsageAggregationResponse = {
    stats: Array<{
        name: string;
        values: Array<{
            date: string;
            total: number;
        }>;
    }>;
};

export type DeploymentStatusResponse = {
    isDeployed: boolean;
    isAvailable: boolean;
    isStabilizing: boolean;
    currentReplicaSet?: string;
    deployments: Array<DeploymentStatus>;
};

export type DeploymentStatus = {
    name: string;
    ready: boolean;
    crash: boolean;
    phase?: string;
    reason?: string;
    createdAt?: string;
    restartCount: number;
    hasPreviousFailure: boolean;
    lastFailure?: {
        containerName: string;
        exitCode?: number;
        reason?: string;
        message?: string;
        finishedAt?: string;
    };
    waitingReason?: string;
};

export type DeploymentLogPayload = {
    type: 'error';
    message: string;
} | {
    type: 'podInfo';
    createdAt: string;
    pod: string;
    initContainers: Array<string>;
    containers: Array<string>;
    waitingReason: string | null;
    restartCount: number;
    hasPreviousFailure: boolean;
    lastFailure?: {
        containerName: string;
        exitCode?: number;
        reason?: string;
        message?: string;
        finishedAt?: string;
    };
} | {
    type: 'initContainerRunning';
    name: string;
} | {
    type: 'initContainerTerminated';
    name: string;
    exitCode: number;
    reason?: string;
    startedAt: string;
    finishedAt: string;
} | {
    type: 'mainContainerWaiting';
    reason: string;
} | {
    type: 'mainContainerCrashBackOff' | 'mainContainerImagePullBackOff';
    reason: string;
    detail?: string;
    restarts: number;
} | {
    type: 'mainContainerRunning';
} | {
    type: 'mainContainerReady';
} | {
    type: 'mainContainerCrashed';
    exitCode: number;
    reason?: string;
    startedAt: string;
    finishedAt: string;
} | {
    type: 'done';
};

export type TeamWithMemberCount = {
    id: string;
    tenantId: string;
    name: string;
    description: string;
    createdAt: string;
    updatedAt: string;
    memberCount: number;
};

export type TeamMember = {
    teamId: string;
    userId: number;
    role: 'member' | 'maintainer';
    createdAt: string;
    updatedAt: string;
};

export type TeamInvitation = {
    id: string;
    teamId: string;
    tenantId: string;
    inviterUserId: number | null;
    email: string;
    role: 'member' | 'maintainer';
    token: string;
    expiresAt: string;
    acceptedAt: string | null;
    createdAt: string;
    updatedAt: string;
};

export type ServerMember = {
    tenantId: string;
    serverId: number;
    role: 'member' | 'admin' | 'maintainer';
    createdAt: string;
    updatedAt: string;
    userId: number;
    teamId: null;
} | {
    tenantId: string;
    serverId: number;
    role: 'member' | 'admin' | 'maintainer';
    createdAt: string;
    updatedAt: string;
    userId: null;
    teamId: string;
};

export type HttpStreamingTransportConfigOutput = {
    type: 'httpstreaming';
    url: string;
    headers?: Array<[
        string,
        string
    ]>;
};

export type StdioTransportConfigOutput = {
    type: 'stdio';
    command: string;
    dockerImage?: string;
    env?: Array<[
        string,
        string
    ]>;
};

export type SseTransportConfigOutput = {
    type: 'sse';
    url: string;
    headers?: Array<[
        string,
        string
    ]>;
};

export type HostedTransportConfigOutput = {
    type: 'hosted';
    runtime: 'node24';
    env?: Array<[
        string,
        string
    ]>;
};

export type TriggerWebhookConfigurationOutput = {
    requiredHeaders?: Array<[
        string,
        string
    ]>;
};

export type TriggerScheduledConfigurationOutput = {
    cron: string;
    timezone: string;
};

export type AuditLogWritable = {
    tenantId: string;
    eventTime: string;
    entityType: string | null;
    entityId: number | null;
    eventName: string;
    userId: number | null;
    details: unknown;
    onlySuperadminVisibility: boolean;
    createdAt: string;
};

export type AuditLogResponseWritable = {
    tenantId: string;
    eventTime: string;
    entityType: string | null;
    entityId: number | null;
    eventName: string;
    userId: number | null;
    details: unknown;
    onlySuperadminVisibility: boolean;
    createdAt: string;
    userEmail: string | null;
    userSub: string | null;
    teamName: string | null;
    serverSlug: string | null;
};

export type PostAuthNativeLoginData = {
    body?: {
        email: string;
        password: string;
        [key: string]: unknown | string;
    };
    path?: never;
    query?: never;
    url: '/auth/native-login';
};

export type PostAuthNativeLoginResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
        user: {
            id: number;
            email: string;
            name: string;
            role: 'member' | 'owner';
            [key: string]: unknown | number | string | ('member' | 'owner');
        };
    };
};

export type PostAuthNativeLoginResponse = PostAuthNativeLoginResponses[keyof PostAuthNativeLoginResponses];

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeResponses = {
    /**
     * Successful response
     */
    200: AuthMetadata;
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type GetAuditLogsByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/audit-logs/{id}';
};

export type GetAuditLogsByIdResponses = {
    /**
     * Successful response
     */
    200: AuditLog;
};

export type GetAuditLogsByIdResponse = GetAuditLogsByIdResponses[keyof GetAuditLogsByIdResponses];

export type GetAuditLogsData = {
    body?: never;
    path?: never;
    query?: {
        page?: string;
        limit?: string;
        userId?: string;
        entityType?: string;
        entityId?: string;
        tenantId?: string;
        startDate?: string;
        endDate?: string;
    };
    url: '/audit-logs';
};

export type GetAuditLogsResponses = {
    /**
     * Successful response
     */
    200: PaginatedAuditLogs;
};

export type GetAuditLogsResponse = GetAuditLogsResponses[keyof GetAuditLogsResponses];

export type PostUsersRequestSetPasswordData = {
    body?: never;
    path?: never;
    query: {
        email: string;
    };
    url: '/users/request-set-password';
};

export type PostUsersRequestSetPasswordResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type PostUsersByUserSubSetPasswordData = {
    body?: {
        token: string;
        password: string;
    };
    path: {
        userSub: string;
    };
    query?: never;
    url: '/users/{userSub}/set-password';
};

export type PostUsersByUserSubSetPasswordResponses = {
    /**
     * Successful response
     */
    200: {
        [key: string]: never;
    };
};

export type PostUsersByUserSubSetPasswordResponse = PostUsersByUserSubSetPasswordResponses[keyof PostUsersByUserSubSetPasswordResponses];

export type GetUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetUsersMeResponses = {
    /**
     * Successful response
     */
    200: {
        user: {
            id: number;
            sub: string;
            tenantId: string;
            name: string;
            email: string;
            role: 'member' | 'owner';
            isDisabled: boolean;
            isServiceAccount: boolean;
            apiKey: string;
            createdAt: string;
            updatedAt: string;
        };
        identities: Array<UserIdentity>;
    };
};

export type GetUsersMeResponse = GetUsersMeResponses[keyof GetUsersMeResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: {
        type?: 'user' | 'service-account' | 'all';
    };
    url: '/users';
};

export type GetUsersResponses = {
    /**
     * Successful response
     */
    200: {
        users: Array<User>;
    };
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PostUsersData = {
    body?: CreateUserRequest;
    path?: never;
    query?: never;
    url: '/users';
};

export type PostUsersResponses = {
    /**
     * Successful response
     */
    200: {
        user: User;
    };
};

export type PostUsersResponse = PostUsersResponses[keyof PostUsersResponses];

export type DeleteUsersByUserSubData = {
    body?: never;
    path: {
        userSub: string;
    };
    query?: never;
    url: '/users/{userSub}';
};

export type DeleteUsersByUserSubResponses = {
    /**
     * Successful response
     */
    200: {
        [key: string]: never;
    };
};

export type DeleteUsersByUserSubResponse = DeleteUsersByUserSubResponses[keyof DeleteUsersByUserSubResponses];

export type GetUsersByUserSubData = {
    body?: never;
    path: {
        userSub: string;
    };
    query?: never;
    url: '/users/{userSub}';
};

export type GetUsersByUserSubResponses = {
    /**
     * Successful response
     */
    200: {
        user: User;
    };
};

export type GetUsersByUserSubResponse = GetUsersByUserSubResponses[keyof GetUsersByUserSubResponses];

export type PutUsersByUserSubData = {
    body?: UpdateUserRequest;
    path: {
        userSub: string;
    };
    query?: never;
    url: '/users/{userSub}';
};

export type PutUsersByUserSubResponses = {
    /**
     * Successful response
     */
    200: {
        user: User;
    };
};

export type PutUsersByUserSubResponse = PutUsersByUserSubResponses[keyof PutUsersByUserSubResponses];

export type GetMcpServersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/mcp-servers';
};

export type GetMcpServersResponses = {
    /**
     * Successful response
     */
    200: {
        servers: Array<{
            id: number;
            slug: string;
            tenantId: string;
            name: string;
            description: string;
            logoUrl?: string;
            authorization: {
                method: 'none' | 'oauth' | 'apikey';
            };
            transportType: 'self' | 'hosted' | 'stdio' | 'httpstreaming' | 'sse';
            transportConfig: HttpStreamingTransportConfigOutput | StdioTransportConfigOutput | SseTransportConfigOutput | {
                type: 'self';
                id: string;
            } | HostedTransportConfigOutput;
            oauthClientConfiguration: null | {
                clientId: string;
                clientSecret: string;
                clientAuthMethod: 'client_secret_basic' | 'client_secret_post' | 'none' | string;
                scopes: string;
                tokenSet?: {
                    accessToken: string;
                    accessTokenExpiresAt?: number;
                    idToken?: string;
                    refreshToken?: string;
                };
            };
            oauthMetadata: null | {
                requiresAuthorization: boolean;
                resource?: {
                    id: string;
                    availableScopes: Array<string>;
                    metadataUrl: string;
                };
                as?: {
                    issuer: string;
                    authorizeEndpoint: string;
                    tokenEndpoint: string;
                    registrationEndpoint?: string;
                    supportsPKCE: boolean;
                    supportedClientAuthMethods: Array<string>;
                    supportsDynamicClientRegistration: boolean;
                    noDynamicClientRegistrationReason?: string | null;
                    serviceDocumentation: string;
                    metadataUrl: string;
                };
            };
            isEnabled: boolean;
            createdAt: string;
            updatedAt: string;
            usage: {
                lastSevenDays: number;
            };
        }>;
    };
};

export type GetMcpServersResponse = GetMcpServersResponses[keyof GetMcpServersResponses];

export type PostMcpServersData = {
    body?: CreateMcpServerRequest;
    path?: never;
    query?: never;
    url: '/mcp-servers';
};

export type PostMcpServersResponses = {
    /**
     * Successful response
     */
    200: {
        server: TenantMcpServer;
        files: Array<ServerFile>;
    };
};

export type PostMcpServersResponse = PostMcpServersResponses[keyof PostMcpServersResponses];

export type DeleteMcpServersByServerSlugData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}';
};

export type DeleteMcpServersByServerSlugResponses = {
    /**
     * Successful response
     */
    200: {
        server: TenantMcpServer;
        files: Array<ServerFile>;
    };
};

export type DeleteMcpServersByServerSlugResponse = DeleteMcpServersByServerSlugResponses[keyof DeleteMcpServersByServerSlugResponses];

export type GetMcpServersByServerSlugData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}';
};

export type GetMcpServersByServerSlugResponses = {
    /**
     * Successful response
     */
    200: {
        server: TenantMcpServer;
        files: Array<ServerFile>;
    };
};

export type GetMcpServersByServerSlugResponse = GetMcpServersByServerSlugResponses[keyof GetMcpServersByServerSlugResponses];

export type PutMcpServersByServerSlugData = {
    body?: UpdateMcpServerRequest;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}';
};

export type PutMcpServersByServerSlugResponses = {
    /**
     * Successful response
     */
    200: {
        server: TenantMcpServer;
        files: Array<ServerFile>;
    };
};

export type PutMcpServersByServerSlugResponse = PutMcpServersByServerSlugResponses[keyof PutMcpServersByServerSlugResponses];

export type GetMcpServersByServerSlugRunningStatusData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/running-status';
};

export type GetMcpServersByServerSlugRunningStatusResponses = {
    /**
     * Successful response
     */
    200: McpServerRunningStatusResponse;
};

export type GetMcpServersByServerSlugRunningStatusResponse = GetMcpServersByServerSlugRunningStatusResponses[keyof GetMcpServersByServerSlugRunningStatusResponses];

export type PostMcpServersByServerSlugStartData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/start';
};

export type PostMcpServersByServerSlugStartResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
        /**
         * Detailed information about why the server could not be started.
         */
        detail?: string;
    };
};

export type PostMcpServersByServerSlugStartResponse = PostMcpServersByServerSlugStartResponses[keyof PostMcpServersByServerSlugStartResponses];

export type PutMcpServersByServerSlugConfigData = {
    body?: {
        type?: 'httpstreaming';
        url?: string;
        headers?: Array<[
            string,
            string
        ]>;
    } | {
        type?: 'hosted';
        runtime?: 'node24';
        env?: Array<[
            string,
            string
        ]>;
    } | {
        type?: 'stdio';
        command?: string;
        dockerImage?: string;
        env?: Array<[
            string,
            string
        ]>;
    } | {
        type?: 'sse';
        url?: string;
        headers?: Array<[
            string,
            string
        ]>;
    };
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/config';
};

export type PutMcpServersByServerSlugConfigResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type PutMcpServersByServerSlugIsEnabledData = {
    body?: {
        value: boolean;
    };
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/isEnabled';
};

export type PutMcpServersByServerSlugIsEnabledResponses = {
    /**
     * Successful response
     */
    200: {
        server: TenantMcpServer;
        files: Array<ServerFile>;
    };
};

export type PutMcpServersByServerSlugIsEnabledResponse = PutMcpServersByServerSlugIsEnabledResponses[keyof PutMcpServersByServerSlugIsEnabledResponses];

export type GetMcpServersByServerSlugToolsData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/tools';
};

export type GetMcpServersByServerSlugToolsResponses = {
    /**
     * Successful response
     */
    200: {
        tools: Array<McpServerTool>;
    };
};

export type GetMcpServersByServerSlugToolsResponse = GetMcpServersByServerSlugToolsResponses[keyof GetMcpServersByServerSlugToolsResponses];

export type GetMcpServersByServerSlugToolsByToolNameData = {
    body?: never;
    path: {
        serverSlug: string;
        toolName: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/tools/{toolName}';
};

export type GetMcpServersByServerSlugToolsByToolNameResponses = {
    /**
     * Successful response
     */
    200: {
        tool: McpServerTool;
    };
};

export type GetMcpServersByServerSlugToolsByToolNameResponse = GetMcpServersByServerSlugToolsByToolNameResponses[keyof GetMcpServersByServerSlugToolsByToolNameResponses];

export type PutMcpServersByServerSlugAllToolsIsEnabledData = {
    body?: {
        value: boolean;
    };
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/all-tools-isEnabled';
};

export type PutMcpServersByServerSlugAllToolsIsEnabledResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
        message: string;
    };
};

export type PutMcpServersByServerSlugAllToolsIsEnabledResponse = PutMcpServersByServerSlugAllToolsIsEnabledResponses[keyof PutMcpServersByServerSlugAllToolsIsEnabledResponses];

export type PutMcpServersByServerSlugToolsByToolNameIsEnabledData = {
    body?: {
        value: boolean;
    };
    path: {
        serverSlug: string;
        toolName: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/tools/{toolName}/isEnabled';
};

export type PutMcpServersByServerSlugToolsByToolNameIsEnabledResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
        message: string;
    };
};

export type PutMcpServersByServerSlugToolsByToolNameIsEnabledResponse = PutMcpServersByServerSlugToolsByToolNameIsEnabledResponses[keyof PutMcpServersByServerSlugToolsByToolNameIsEnabledResponses];

export type PostMcpServersByServerSlugToolsByToolNameCallData = {
    body?: {
        args: {
            [key: string]: unknown;
        };
    };
    path: {
        serverSlug: string;
        toolName: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/tools/{toolName}/call';
};

export type PostMcpServersByServerSlugToolsByToolNameCallResponses = {
    /**
     * Successful response
     */
    200: {
        tool: McpServerTool;
    };
};

export type PostMcpServersByServerSlugToolsByToolNameCallResponse = PostMcpServersByServerSlugToolsByToolNameCallResponses[keyof PostMcpServersByServerSlugToolsByToolNameCallResponses];

export type GetMcpServersByServerSlugMembersData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/members/';
};

export type GetMcpServersByServerSlugMembersResponses = {
    /**
     * Successful response
     */
    200: GetMembersResponse;
};

export type GetMcpServersByServerSlugMembersResponse = GetMcpServersByServerSlugMembersResponses[keyof GetMcpServersByServerSlugMembersResponses];

export type DeleteMcpServersByServerSlugMembersByMemberTypeByIdData = {
    body?: never;
    path: {
        serverSlug: string;
        memberType: 'users' | 'teams';
        id: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/members/{memberType}/{id}';
};

export type DeleteMcpServersByServerSlugMembersByMemberTypeByIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type DeleteMcpServersByServerSlugMembersByMemberTypeByIdResponse = DeleteMcpServersByServerSlugMembersByMemberTypeByIdResponses[keyof DeleteMcpServersByServerSlugMembersByMemberTypeByIdResponses];

export type PutMcpServersByServerSlugMembersByMemberTypeByIdData = {
    body?: {
        role: 'member' | 'admin' | 'maintainer';
    };
    path: {
        serverSlug: string;
        memberType: 'users' | 'teams';
        id: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/members/{memberType}/{id}';
};

export type PutMcpServersByServerSlugMembersByMemberTypeByIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PutMcpServersByServerSlugMembersByMemberTypeByIdResponse = PutMcpServersByServerSlugMembersByMemberTypeByIdResponses[keyof PutMcpServersByServerSlugMembersByMemberTypeByIdResponses];

export type GetMcpServersByServerSlugSourceCodeData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/source-code';
};

export type GetMcpServersByServerSlugSourceCodeResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type PutMcpServersByServerSlugSourceCodeData = {
    body?: {
        file: unknown;
    };
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/source-code';
};

export type PutMcpServersByServerSlugSourceCodeResponses = {
    /**
     * Successful response
     */
    200: UploadSourceCodeResponse;
};

export type PutMcpServersByServerSlugSourceCodeResponse = PutMcpServersByServerSlugSourceCodeResponses[keyof PutMcpServersByServerSlugSourceCodeResponses];

export type GetMcpServersByServerSlugFilesData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/files';
};

export type GetMcpServersByServerSlugFilesResponses = {
    /**
     * Successful response
     */
    200: {
        files: Array<ServerFile>;
    };
};

export type GetMcpServersByServerSlugFilesResponse = GetMcpServersByServerSlugFilesResponses[keyof GetMcpServersByServerSlugFilesResponses];

export type PostMcpServersByServerSlugFilesData = {
    body?: never;
    path: {
        serverSlug: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/files';
};

export type PostMcpServersByServerSlugFilesResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
    };
};

export type PostMcpServersByServerSlugFilesResponse = PostMcpServersByServerSlugFilesResponses[keyof PostMcpServersByServerSlugFilesResponses];

export type PutMcpServersByServerSlugFilesByFileIdNameData = {
    body?: {
        filename: string;
    };
    path: {
        serverSlug: string;
        fileId: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/files/{fileId}/name';
};

export type PutMcpServersByServerSlugFilesByFileIdNameResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PutMcpServersByServerSlugFilesByFileIdNameResponse = PutMcpServersByServerSlugFilesByFileIdNameResponses[keyof PutMcpServersByServerSlugFilesByFileIdNameResponses];

export type DeleteMcpServersByServerSlugFilesByFileIdData = {
    body?: never;
    path: {
        serverSlug: string;
        fileId: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/files/{fileId}';
};

export type DeleteMcpServersByServerSlugFilesByFileIdResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type GetMcpServersByServerSlugFilesByFileIdData = {
    body?: never;
    path: {
        serverSlug: string;
        fileId: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/files/{fileId}';
};

export type GetMcpServersByServerSlugFilesByFileIdResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type PutMcpServersByServerSlugFilesByFileIdData = {
    body?: never;
    path: {
        serverSlug: string;
        fileId: string;
    };
    query?: never;
    url: '/mcp-servers/{serverSlug}/files/{fileId}';
};

export type PutMcpServersByServerSlugFilesByFileIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PutMcpServersByServerSlugFilesByFileIdResponse = PutMcpServersByServerSlugFilesByFileIdResponses[keyof PutMcpServersByServerSlugFilesByFileIdResponses];

export type PostSignupData = {
    body?: {
        tenantDisplayName: string;
        tenantSlug: string;
        email: string;
        recaptchaToken?: string;
    };
    path?: never;
    query?: never;
    url: '/signup';
};

export type PostSignupResponses = {
    /**
     * Successful response
     */
    200: {
        [key: string]: never;
    };
};

export type PostSignupResponse = PostSignupResponses[keyof PostSignupResponses];

export type GetTenantsByTenantIdSigninMethodsData = {
    body?: never;
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/tenants/{tenantId}/signin-methods';
};

export type GetTenantsByTenantIdSigninMethodsResponses = {
    /**
     * Successful response
     */
    200: {
        displayName: string;
        native: boolean;
        external: boolean;
    };
};

export type GetTenantsByTenantIdSigninMethodsResponse = GetTenantsByTenantIdSigninMethodsResponses[keyof GetTenantsByTenantIdSigninMethodsResponses];

export type GetTenantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tenants/';
};

export type GetTenantsResponses = {
    /**
     * Successful response
     */
    200: {
        tenants: Array<Tenant>;
    };
};

export type GetTenantsResponse = GetTenantsResponses[keyof GetTenantsResponses];

export type DeleteTenantsByTenantIdData = {
    body?: never;
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/tenants/{tenantId}';
};

export type DeleteTenantsByTenantIdResponses = {
    /**
     * Successful response
     */
    200: {
        [key: string]: never;
    };
};

export type DeleteTenantsByTenantIdResponse = DeleteTenantsByTenantIdResponses[keyof DeleteTenantsByTenantIdResponses];

export type GetTenantsByTenantIdData = {
    body?: never;
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/tenants/{tenantId}';
};

export type GetTenantsByTenantIdResponses = {
    /**
     * Successful response
     */
    200: {
        tenant: Tenant;
    };
};

export type GetTenantsByTenantIdResponse = GetTenantsByTenantIdResponses[keyof GetTenantsByTenantIdResponses];

export type PutTenantsByTenantIdData = {
    body?: UpdateTenantRequest;
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/tenants/{tenantId}';
};

export type PutTenantsByTenantIdResponses = {
    /**
     * Successful response
     */
    200: {
        tenant: Tenant;
    };
};

export type PutTenantsByTenantIdResponse = PutTenantsByTenantIdResponses[keyof PutTenantsByTenantIdResponses];

export type GetTenantsByTenantIdSubscriptionData = {
    body?: never;
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/tenants/{tenantId}/subscription';
};

export type GetTenantsByTenantIdSubscriptionResponses = {
    /**
     * Successful response
     */
    200: {
        subscriptionPlan: string;
        subscriptionSeats: number;
        subscription: {
            trialEndsAt: string | null;
            status: string;
            currentPeriodEnd: string;
            paymentType?: string | null;
            cancelsAt: string | null;
            perSeatAmount: number;
            currency: string;
            card: {
                valid: boolean;
                brand: string;
                last4: string;
                expiresYear: number;
                expiresMonth: number;
            } | null;
        } | null;
    };
};

export type GetTenantsByTenantIdSubscriptionResponse = GetTenantsByTenantIdSubscriptionResponses[keyof GetTenantsByTenantIdSubscriptionResponses];

export type PutTenantsByTenantIdIsMcpAuthorizationApiKeyEnabledData = {
    body?: {
        isEnabled: boolean;
    };
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/tenants/{tenantId}/is-mcp-authorization-api-key-enabled';
};

export type PutTenantsByTenantIdIsMcpAuthorizationApiKeyEnabledResponses = {
    /**
     * Successful response
     */
    200: {
        isEnabled: boolean;
    };
};

export type PutTenantsByTenantIdIsMcpAuthorizationApiKeyEnabledResponse = PutTenantsByTenantIdIsMcpAuthorizationApiKeyEnabledResponses[keyof PutTenantsByTenantIdIsMcpAuthorizationApiKeyEnabledResponses];

export type GetTenantsByTenantIdDiscoverSamlMetadataData = {
    body?: never;
    path: {
        tenantId: string;
    };
    query: {
        url: string;
    };
    url: '/tenants/{tenantId}/discover-saml-metadata';
};

export type GetTenantsByTenantIdDiscoverSamlMetadataResponses = {
    /**
     * Successful response
     */
    200: string;
};

export type GetTenantsByTenantIdDiscoverSamlMetadataResponse = GetTenantsByTenantIdDiscoverSamlMetadataResponses[keyof GetTenantsByTenantIdDiscoverSamlMetadataResponses];

export type GetTenantSamlMetadataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tenant-saml-metadata';
};

export type GetTenantSamlMetadataResponses = {
    /**
     * Successful response
     */
    200: string;
};

export type GetTenantSamlMetadataResponse = GetTenantSamlMetadataResponses[keyof GetTenantSamlMetadataResponses];

export type GetQuotaAndUsageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/quota-and-usage';
};

export type GetQuotaAndUsageResponses = {
    /**
     * Successful response
     */
    200: {
        quotas: {
            agentRuns: {
                quota: number;
                current: number;
                remaining: number;
                periodUnit: 'hour' | 'day' | 'week' | 'month';
                periodEnd: string;
                periodStart: string;
            };
            agents: {
                quota: number;
                current: number;
                remaining: number;
            };
            accounts: {
                quota: number;
                current: number;
                remaining: number;
            };
            mcpServers: {
                quota: number;
                current: number;
                remaining: number;
            };
        };
    };
};

export type GetQuotaAndUsageResponse = GetQuotaAndUsageResponses[keyof GetQuotaAndUsageResponses];

export type GetAgentsLlmApisData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agents/llm-apis';
};

export type GetAgentsLlmApisResponses = {
    /**
     * Successful response
     */
    200: {
        apis: Array<LlmApi>;
    };
};

export type GetAgentsLlmApisResponse = GetAgentsLlmApisResponses[keyof GetAgentsLlmApisResponses];

export type GetAgentsLlmModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agents/llm-models';
};

export type GetAgentsLlmModelsResponses = {
    /**
     * Successful response
     */
    200: {
        models: Array<LlmModel>;
    };
};

export type GetAgentsLlmModelsResponse = GetAgentsLlmModelsResponses[keyof GetAgentsLlmModelsResponses];

export type GetAgentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agents';
};

export type GetAgentsResponses = {
    /**
     * Successful response
     */
    200: {
        agents: Array<Agent>;
    };
};

export type GetAgentsResponse = GetAgentsResponses[keyof GetAgentsResponses];

export type PostAgentsData = {
    body?: {
        modelId: string;
        llmApiId: string;
        apiKeyId: string | null;
        name: string;
        description: string;
        modelConfiguration: {
            [key: string]: unknown;
        };
        systemMessage: string;
        prompt: string;
        isEnabled: boolean;
        inputSchema: string;
        outputSchema: string;
    };
    path?: never;
    query?: never;
    url: '/agents';
};

export type PostAgentsResponses = {
    /**
     * Successful response
     */
    200: {
        agent: Agent;
        model: LlmModel;
        key: TenantLlmKey | null;
        api: LlmApi;
        mcpServers: Array<TenantMcpServer>;
        files: Array<AgentContextFile>;
    };
};

export type PostAgentsResponse = PostAgentsResponses[keyof PostAgentsResponses];

export type DeleteAgentsByAgentIdData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}';
};

export type DeleteAgentsByAgentIdResponses = {
    /**
     * Successful response
     */
    200: {
        [key: string]: never;
    };
};

export type DeleteAgentsByAgentIdResponse = DeleteAgentsByAgentIdResponses[keyof DeleteAgentsByAgentIdResponses];

export type GetAgentsByAgentIdData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}';
};

export type GetAgentsByAgentIdResponses = {
    /**
     * Successful response
     */
    200: {
        agent: Agent;
        model: LlmModel;
        key: TenantLlmKey | null;
        api: LlmApi;
        mcpServers: Array<TenantMcpServer>;
        files: Array<AgentContextFile>;
    };
};

export type GetAgentsByAgentIdResponse = GetAgentsByAgentIdResponses[keyof GetAgentsByAgentIdResponses];

export type PutAgentsByAgentIdData = {
    body?: {
        apiKeyId: string | null;
        name: string;
        description: string;
        modelConfiguration: {
            [key: string]: unknown;
        };
        systemMessage: string;
        prompt: string;
        isEnabled: boolean;
        inputSchema: string;
        outputSchema: string;
    };
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}';
};

export type PutAgentsByAgentIdResponses = {
    /**
     * Successful response
     */
    200: {
        agent: Agent;
        model: LlmModel;
        key: TenantLlmKey | null;
        api: LlmApi;
        mcpServers: Array<TenantMcpServer>;
        files: Array<AgentContextFile>;
    };
};

export type PutAgentsByAgentIdResponse = PutAgentsByAgentIdResponses[keyof PutAgentsByAgentIdResponses];

export type PutAgentsByAgentIdEnabledData = {
    body?: {
        isEnabled: boolean;
    };
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/enabled';
};

export type PutAgentsByAgentIdEnabledResponses = {
    /**
     * Successful response
     */
    200: {
        isEnabled: boolean;
    };
};

export type PutAgentsByAgentIdEnabledResponse = PutAgentsByAgentIdEnabledResponses[keyof PutAgentsByAgentIdEnabledResponses];

export type PostAgentsByAgentIdChatData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/chat';
};

export type PostAgentsByAgentIdChatResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
    };
};

export type PostAgentsByAgentIdChatResponse = PostAgentsByAgentIdChatResponses[keyof PostAgentsByAgentIdChatResponses];

export type PostAgentsChatByIdMessageData = {
    body?: {
        input: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/agents/chat/{id}/message';
};

export type PostAgentsChatByIdMessageResponses = {
    /**
     * Chat message received
     */
    200: {
        result: unknown;
    };
};

export type PostAgentsChatByIdMessageResponse = PostAgentsChatByIdMessageResponses[keyof PostAgentsChatByIdMessageResponses];

export type GetAgentsByAgentIdContextFilesData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/context-files';
};

export type GetAgentsByAgentIdContextFilesResponses = {
    /**
     * Successful response
     */
    200: {
        files: Array<AgentContextFile>;
    };
};

export type GetAgentsByAgentIdContextFilesResponse = GetAgentsByAgentIdContextFilesResponses[keyof GetAgentsByAgentIdContextFilesResponses];

export type PostAgentsByAgentIdContextFilesData = {
    body?: {
        file: Blob | File;
    };
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/context-files';
};

export type PostAgentsByAgentIdContextFilesResponses = {
    /**
     * Successful response
     */
    200: {
        file: AgentContextFile;
    };
};

export type PostAgentsByAgentIdContextFilesResponse = PostAgentsByAgentIdContextFilesResponses[keyof PostAgentsByAgentIdContextFilesResponses];

export type DeleteAgentsByAgentIdContextFilesByFileIdData = {
    body?: never;
    path: {
        agentId: string;
        fileId: string;
    };
    query?: never;
    url: '/agents/{agentId}/context-files/{fileId}';
};

export type DeleteAgentsByAgentIdContextFilesByFileIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type DeleteAgentsByAgentIdContextFilesByFileIdResponse = DeleteAgentsByAgentIdContextFilesByFileIdResponses[keyof DeleteAgentsByAgentIdContextFilesByFileIdResponses];

export type GetAgentsByAgentIdContextFilesByFileIdData = {
    body?: never;
    path: {
        agentId: string;
        fileId: string;
    };
    query?: never;
    url: '/agents/{agentId}/context-files/{fileId}';
};

export type GetAgentsByAgentIdContextFilesByFileIdResponses = {
    /**
     * Successful response
     */
    200: {
        file: AgentContextFile;
    };
};

export type GetAgentsByAgentIdContextFilesByFileIdResponse = GetAgentsByAgentIdContextFilesByFileIdResponses[keyof GetAgentsByAgentIdContextFilesByFileIdResponses];

export type GetAgentsByAgentIdMcpServersData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/mcp-servers';
};

export type GetAgentsByAgentIdMcpServersResponses = {
    /**
     * Successful response
     */
    200: {
        mcpServers: Array<TenantMcpServer>;
    };
};

export type GetAgentsByAgentIdMcpServersResponse = GetAgentsByAgentIdMcpServersResponses[keyof GetAgentsByAgentIdMcpServersResponses];

export type PostAgentsByAgentIdMcpServersData = {
    body?: {
        mcpServerId: number;
    };
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/mcp-servers';
};

export type PostAgentsByAgentIdMcpServersResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PostAgentsByAgentIdMcpServersResponse = PostAgentsByAgentIdMcpServersResponses[keyof PostAgentsByAgentIdMcpServersResponses];

export type DeleteAgentsByAgentIdMcpServersByMcpServerIdData = {
    body?: never;
    path: {
        agentId: string;
        mcpServerId: string;
    };
    query?: never;
    url: '/agents/{agentId}/mcp-servers/{mcpServerId}';
};

export type DeleteAgentsByAgentIdMcpServersByMcpServerIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type DeleteAgentsByAgentIdMcpServersByMcpServerIdResponse = DeleteAgentsByAgentIdMcpServersByMcpServerIdResponses[keyof DeleteAgentsByAgentIdMcpServersByMcpServerIdResponses];

export type GetAgentsByAgentIdRunsData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/runs';
};

export type GetAgentsByAgentIdRunsResponses = {
    /**
     * Successful response
     */
    200: {
        runs: Array<AgentRun>;
    };
};

export type GetAgentsByAgentIdRunsResponse = GetAgentsByAgentIdRunsResponses[keyof GetAgentsByAgentIdRunsResponses];

export type PostAgentsByAgentIdRunsData = {
    body?: {
        customPrompt?: string;
        limitMcpServers?: Array<string>;
        limitTools?: Array<string>;
    };
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/runs';
};

export type PostAgentsByAgentIdRunsResponses = {
    /**
     * Successful response
     */
    200: {
        runId: string;
    };
};

export type PostAgentsByAgentIdRunsResponse = PostAgentsByAgentIdRunsResponses[keyof PostAgentsByAgentIdRunsResponses];

export type GetAgentsByAgentIdRunsByRunIdData = {
    body?: never;
    path: {
        agentId: string;
        runId: string;
    };
    query?: never;
    url: '/agents/{agentId}/runs/{runId}';
};

export type GetAgentsByAgentIdRunsByRunIdResponses = {
    /**
     * Successful response
     */
    200: {
        run: AgentRun;
        usage: TenantUsage | null;
        toolCalls: Array<AgentRunToolCall>;
    };
};

export type GetAgentsByAgentIdRunsByRunIdResponse = GetAgentsByAgentIdRunsByRunIdResponses[keyof GetAgentsByAgentIdRunsByRunIdResponses];

export type GetTriggersData = {
    body?: never;
    path?: never;
    query?: {
        agentId?: string;
    };
    url: '/triggers';
};

export type GetTriggersResponses = {
    /**
     * Successful response
     */
    200: {
        triggers: Array<Trigger>;
    };
};

export type GetTriggersResponse = GetTriggersResponses[keyof GetTriggersResponses];

export type PostTriggersData = {
    body?: {
        name: string;
        type: 'webhook' | 'scheduled';
        configuration: TriggerWebhookConfiguration | TriggerScheduledConfiguration;
        isEnabled: boolean;
    };
    path?: never;
    query?: never;
    url: '/triggers';
};

export type PostTriggersResponses = {
    /**
     * Successful response
     */
    200: {
        trigger: Trigger;
    };
};

export type PostTriggersResponse = PostTriggersResponses[keyof PostTriggersResponses];

export type DeleteTriggersByTriggerIdData = {
    body?: never;
    path: {
        triggerId: string;
    };
    query?: never;
    url: '/triggers/{triggerId}';
};

export type DeleteTriggersByTriggerIdResponses = {
    /**
     * Successful response
     */
    200: {
        [key: string]: never;
    };
};

export type DeleteTriggersByTriggerIdResponse = DeleteTriggersByTriggerIdResponses[keyof DeleteTriggersByTriggerIdResponses];

export type GetTriggersByTriggerIdData = {
    body?: never;
    path: {
        triggerId: string;
    };
    query?: never;
    url: '/triggers/{triggerId}';
};

export type GetTriggersByTriggerIdResponses = {
    /**
     * Successful response
     */
    200: {
        trigger: Trigger;
        targets: Array<TriggerTarget>;
    };
};

export type GetTriggersByTriggerIdResponse = GetTriggersByTriggerIdResponses[keyof GetTriggersByTriggerIdResponses];

export type PutTriggersByTriggerIdData = {
    body?: {
        name: string;
        configuration: TriggerWebhookConfiguration | TriggerScheduledConfiguration;
        isEnabled: boolean;
    };
    path: {
        triggerId: string;
    };
    query?: never;
    url: '/triggers/{triggerId}';
};

export type PutTriggersByTriggerIdResponses = {
    /**
     * Successful response
     */
    200: {
        trigger: Trigger;
    };
};

export type PutTriggersByTriggerIdResponse = PutTriggersByTriggerIdResponses[keyof PutTriggersByTriggerIdResponses];

export type PostTriggersByTriggerIdInvokeData = {
    body?: never;
    path: {
        triggerId: string;
    };
    query?: never;
    url: '/triggers/{triggerId}/invoke';
};

export type PostTriggersByTriggerIdInvokeResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type PutTriggersByTriggerIdEnabledData = {
    body?: {
        isEnabled: boolean;
    };
    path: {
        triggerId: string;
    };
    query?: never;
    url: '/triggers/{triggerId}/enabled';
};

export type PutTriggersByTriggerIdEnabledResponses = {
    /**
     * Successful response
     */
    200: {
        isEnabled: boolean;
    };
};

export type PutTriggersByTriggerIdEnabledResponse = PutTriggersByTriggerIdEnabledResponses[keyof PutTriggersByTriggerIdEnabledResponses];

export type GetTriggersByTriggerIdInvocationsData = {
    body?: never;
    path: {
        triggerId: string;
    };
    query?: never;
    url: '/triggers/{triggerId}/invocations';
};

export type GetTriggersByTriggerIdInvocationsResponses = {
    /**
     * Successful response
     */
    200: {
        invocations: Array<TriggerInvocation>;
    };
};

export type GetTriggersByTriggerIdInvocationsResponse = GetTriggersByTriggerIdInvocationsResponses[keyof GetTriggersByTriggerIdInvocationsResponses];

export type GetTriggersByTriggerIdInvocationsByInvocationIdData = {
    body?: never;
    path: {
        triggerId: string;
        invocationId: string;
    };
    query?: never;
    url: '/triggers/{triggerId}/invocations/{invocationId}';
};

export type GetTriggersByTriggerIdInvocationsByInvocationIdResponses = {
    /**
     * Successful response
     */
    200: {
        invocation: TriggerInvocation;
    };
};

export type GetTriggersByTriggerIdInvocationsByInvocationIdResponse = GetTriggersByTriggerIdInvocationsByInvocationIdResponses[keyof GetTriggersByTriggerIdInvocationsByInvocationIdResponses];

export type GetTriggersByTriggerIdTargetsData = {
    body?: never;
    path: {
        triggerId: string;
    };
    query?: never;
    url: '/triggers/{triggerId}/targets';
};

export type GetTriggersByTriggerIdTargetsResponses = {
    /**
     * Successful response
     */
    200: {
        agentIds: Array<string>;
    };
};

export type GetTriggersByTriggerIdTargetsResponse = GetTriggersByTriggerIdTargetsResponses[keyof GetTriggersByTriggerIdTargetsResponses];

export type PostTriggersByTriggerIdTargetsData = {
    body?: {
        agentId: string;
    };
    path: {
        triggerId: string;
    };
    query?: never;
    url: '/triggers/{triggerId}/targets';
};

export type PostTriggersByTriggerIdTargetsResponses = {
    /**
     * Successful response
     */
    200: {
        agentIds: Array<string>;
    };
};

export type PostTriggersByTriggerIdTargetsResponse = PostTriggersByTriggerIdTargetsResponses[keyof PostTriggersByTriggerIdTargetsResponses];

export type DeleteTriggersByTriggerIdTargetsByAgentIdData = {
    body?: never;
    path: {
        triggerId: string;
        agentId: string;
    };
    query?: never;
    url: '/triggers/{triggerId}/targets/{agentId}';
};

export type DeleteTriggersByTriggerIdTargetsByAgentIdResponses = {
    /**
     * Successful response
     */
    200: {
        agentIds: Array<string>;
    };
};

export type DeleteTriggersByTriggerIdTargetsByAgentIdResponse = DeleteTriggersByTriggerIdTargetsByAgentIdResponses[keyof DeleteTriggersByTriggerIdTargetsByAgentIdResponses];

export type GetLlmApiKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/llm-api-keys';
};

export type GetLlmApiKeysResponses = {
    /**
     * Successful response
     */
    200: {
        apiKeys: Array<TenantLlmKey>;
    };
};

export type GetLlmApiKeysResponse = GetLlmApiKeysResponses[keyof GetLlmApiKeysResponses];

export type PostLlmApiKeysData = {
    body?: {
        name: string;
        key: string;
        llmApiId: string;
        extra?: {
            [key: string]: string;
        };
    };
    path?: never;
    query?: never;
    url: '/llm-api-keys';
};

export type PostLlmApiKeysResponses = {
    /**
     * Successful response
     */
    200: {
        [key: string]: never;
    };
};

export type PostLlmApiKeysResponse = PostLlmApiKeysResponses[keyof PostLlmApiKeysResponses];

export type DeleteLlmApiKeysByKeyIdData = {
    body?: never;
    path: {
        keyId: string;
    };
    query?: never;
    url: '/llm-api-keys/{keyId}';
};

export type DeleteLlmApiKeysByKeyIdResponses = {
    /**
     * Successful response
     */
    200: {
        [key: string]: never;
    };
};

export type DeleteLlmApiKeysByKeyIdResponse = DeleteLlmApiKeysByKeyIdResponses[keyof DeleteLlmApiKeysByKeyIdResponses];

export type PutLlmApiKeysByKeyIdData = {
    body?: {
        name: string;
        key: string;
        extra?: {
            [key: string]: string;
        };
    };
    path: {
        keyId: string;
    };
    query?: never;
    url: '/llm-api-keys/{keyId}';
};

export type PutLlmApiKeysByKeyIdResponses = {
    /**
     * Successful response
     */
    200: {
        [key: string]: never;
    };
};

export type PutLlmApiKeysByKeyIdResponse = PutLlmApiKeysByKeyIdResponses[keyof PutLlmApiKeysByKeyIdResponses];

export type PutLlmApiKeysByKeyIdEnabledData = {
    body?: {
        isEnabled: boolean;
    };
    path: {
        keyId: string;
    };
    query?: never;
    url: '/llm-api-keys/{keyId}/enabled';
};

export type PutLlmApiKeysByKeyIdEnabledResponses = {
    /**
     * Successful response
     */
    200: {
        [key: string]: never;
    };
};

export type PutLlmApiKeysByKeyIdEnabledResponse = PutLlmApiKeysByKeyIdEnabledResponses[keyof PutLlmApiKeysByKeyIdEnabledResponses];

export type PostPlaygroundConvertTokenData = {
    body?: {
        id: string;
        displayName: string;
        email: string;
    };
    path?: never;
    query?: never;
    url: '/playground/convert-token';
};

export type PostPlaygroundConvertTokenResponses = {
    /**
     * Successful response
     */
    200: {
        token: string;
    };
};

export type PostPlaygroundConvertTokenResponse = PostPlaygroundConvertTokenResponses[keyof PostPlaygroundConvertTokenResponses];

export type GetUsageData = {
    body?: never;
    path?: never;
    query?: {
        page?: string;
        limit?: string;
        type?: 'AgentRun' | 'FreeCredit' | 'PaidCredit' | 'McpToolCall';
        startDate?: string;
        endDate?: string;
        /**
         * JSON encoded string of { [key: string]: string | boolean | number }. Only records whose meta object matches this structure will be returned.
         */
        meta?: string;
    };
    url: '/usage';
};

export type GetUsageResponses = {
    /**
     * Successful response
     */
    200: {
        data: Array<TenantUsage>;
        pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
            hasNext: boolean;
            hasPrev: boolean;
        };
    };
};

export type GetUsageResponse = GetUsageResponses[keyof GetUsageResponses];

export type GetUsageAggregationData = {
    body?: never;
    path?: never;
    query: {
        periodStart: string;
        periodEnd: string;
    };
    url: '/usage/aggregation';
};

export type GetUsageAggregationResponses = {
    /**
     * Successful response
     */
    200: UsageAggregationResponse;
};

export type GetUsageAggregationResponse = GetUsageAggregationResponses[keyof GetUsageAggregationResponses];

export type GetUsageByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/usage/{id}';
};

export type GetUsageByIdResponses = {
    /**
     * Successful response
     */
    200: {
        usage: TenantUsage;
    };
};

export type GetUsageByIdResponse = GetUsageByIdResponses[keyof GetUsageByIdResponses];

export type PostCreditsPurchaseData = {
    body?: PurchaseCreditsRequest;
    path?: never;
    query?: never;
    url: '/credits/purchase';
};

export type PostCreditsPurchaseResponses = {
    /**
     * Successful response
     */
    200: {
        checkoutUrl: string;
        sessionId: string;
    };
};

export type PostCreditsPurchaseResponse = PostCreditsPurchaseResponses[keyof PostCreditsPurchaseResponses];

export type GetDeploymentsStatusData = {
    body?: never;
    path?: never;
    query?: {
        hostedFunctionId?: string;
        serverSlug?: string;
    };
    url: '/deployments/status';
};

export type GetDeploymentsStatusResponses = {
    /**
     * Successful response
     */
    200: DeploymentStatusResponse;
};

export type GetDeploymentsStatusResponse = GetDeploymentsStatusResponses[keyof GetDeploymentsStatusResponses];

export type GetDeploymentsLogsData = {
    body?: never;
    path?: never;
    query: {
        podName: string;
        previous?: 'true' | 'false';
    };
    url: '/deployments/logs';
};

export type GetDeploymentsLogsResponses = {
    /**
     * Successful response
     */
    200: {
        logs: {
            stdout: string;
            stderr: string;
        };
    };
};

export type GetDeploymentsLogsResponse = GetDeploymentsLogsResponses[keyof GetDeploymentsLogsResponses];

export type GetDeploymentsToolsData = {
    body?: never;
    path?: never;
    query: {
        podName?: string;
        serverSlug: string;
    };
    url: '/deployments/tools';
};

export type GetDeploymentsToolsResponses = {
    /**
     * Successful response
     */
    200: {
        tools: Array<{
            name: string;
        }>;
    };
};

export type GetDeploymentsToolsResponse = GetDeploymentsToolsResponses[keyof GetDeploymentsToolsResponses];

export type GetDeploymentsDeploymentLogsData = {
    body?: never;
    path?: never;
    query?: {
        hostedFunctionId?: string;
        serverSlug?: string;
    };
    url: '/deployments/deployment-logs';
};

export type GetDeploymentsDeploymentLogsResponses = {
    /**
     * Successful response
     */
    200: Array<{
        type: 'error' | 'data';
        data: Array<DeploymentLogPayload>;
    }>;
};

export type GetDeploymentsDeploymentLogsResponse = GetDeploymentsDeploymentLogsResponses[keyof GetDeploymentsDeploymentLogsResponses];

export type GetTeamsData = {
    body?: never;
    path?: never;
    query?: {
        userSub?: string;
    };
    url: '/teams';
};

export type GetTeamsResponses = {
    /**
     * Successful response
     */
    200: {
        teams: Array<TeamWithMemberCount>;
    };
};

export type GetTeamsResponse = GetTeamsResponses[keyof GetTeamsResponses];

export type PostTeamsData = {
    body?: {
        name: string;
        description: string;
    };
    path?: never;
    query?: never;
    url: '/teams';
};

export type PostTeamsResponses = {
    /**
     * Successful response
     */
    200: {
        team: TeamWithMemberCount;
    };
};

export type PostTeamsResponse = PostTeamsResponses[keyof PostTeamsResponses];

export type DeleteTeamsByTeamIdData = {
    body?: never;
    path: {
        teamId: string;
    };
    query?: never;
    url: '/teams/{teamId}';
};

export type DeleteTeamsByTeamIdResponses = {
    /**
     * Successful response
     */
    200: {
        [key: string]: never;
    };
};

export type DeleteTeamsByTeamIdResponse = DeleteTeamsByTeamIdResponses[keyof DeleteTeamsByTeamIdResponses];

export type GetTeamsByTeamIdData = {
    body?: never;
    path: {
        teamId: string;
    };
    query?: never;
    url: '/teams/{teamId}';
};

export type GetTeamsByTeamIdResponses = {
    /**
     * Successful response
     */
    200: {
        team: TeamWithMemberCount;
    };
};

export type GetTeamsByTeamIdResponse = GetTeamsByTeamIdResponses[keyof GetTeamsByTeamIdResponses];

export type PutTeamsByTeamIdData = {
    body?: {
        name: string;
        description: string;
    };
    path: {
        teamId: string;
    };
    query?: never;
    url: '/teams/{teamId}';
};

export type PutTeamsByTeamIdResponses = {
    /**
     * Successful response
     */
    200: {
        team: TeamWithMemberCount;
    };
};

export type PutTeamsByTeamIdResponse = PutTeamsByTeamIdResponses[keyof PutTeamsByTeamIdResponses];

export type GetTeamsByTeamIdMembersData = {
    body?: never;
    path: {
        teamId: string;
    };
    query?: never;
    url: '/teams/{teamId}/members';
};

export type GetTeamsByTeamIdMembersResponses = {
    /**
     * Successful response
     */
    200: {
        members: Array<{
            member: TeamMember;
            user: User;
        }>;
    };
};

export type GetTeamsByTeamIdMembersResponse = GetTeamsByTeamIdMembersResponses[keyof GetTeamsByTeamIdMembersResponses];

export type PostTeamsByTeamIdMembersData = {
    body?: {
        userId: string;
        role: 'member' | 'maintainer';
    };
    path: {
        teamId: string;
    };
    query?: never;
    url: '/teams/{teamId}/members';
};

export type PostTeamsByTeamIdMembersResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PostTeamsByTeamIdMembersResponse = PostTeamsByTeamIdMembersResponses[keyof PostTeamsByTeamIdMembersResponses];

export type DeleteTeamsByTeamIdMembersByUserIdData = {
    body?: never;
    path: {
        teamId: string;
        userId: string;
    };
    query?: never;
    url: '/teams/{teamId}/members/{userId}';
};

export type DeleteTeamsByTeamIdMembersByUserIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type DeleteTeamsByTeamIdMembersByUserIdResponse = DeleteTeamsByTeamIdMembersByUserIdResponses[keyof DeleteTeamsByTeamIdMembersByUserIdResponses];

export type PutTeamsByTeamIdMembersByUserIdData = {
    body?: {
        role: 'member' | 'maintainer';
    };
    path: {
        teamId: string;
        userId: string;
    };
    query?: never;
    url: '/teams/{teamId}/members/{userId}';
};

export type PutTeamsByTeamIdMembersByUserIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PutTeamsByTeamIdMembersByUserIdResponse = PutTeamsByTeamIdMembersByUserIdResponses[keyof PutTeamsByTeamIdMembersByUserIdResponses];

export type GetTeamsByTeamIdInvitationsData = {
    body?: never;
    path: {
        teamId: string;
    };
    query?: never;
    url: '/teams/{teamId}/invitations';
};

export type GetTeamsByTeamIdInvitationsResponses = {
    /**
     * Successful response
     */
    200: {
        invitations: Array<TeamInvitation>;
    };
};

export type GetTeamsByTeamIdInvitationsResponse = GetTeamsByTeamIdInvitationsResponses[keyof GetTeamsByTeamIdInvitationsResponses];

export type PostTeamsByTeamIdInvitationsData = {
    body?: {
        email: string;
        role: 'member' | 'maintainer';
    };
    path: {
        teamId: string;
    };
    query?: never;
    url: '/teams/{teamId}/invitations';
};

export type PostTeamsByTeamIdInvitationsResponses = {
    /**
     * Successful response
     */
    200: {
        invitation: TeamInvitation;
    };
};

export type PostTeamsByTeamIdInvitationsResponse = PostTeamsByTeamIdInvitationsResponses[keyof PostTeamsByTeamIdInvitationsResponses];

export type DeleteTeamsByTeamIdInvitationsByInvitationIdData = {
    body?: never;
    path: {
        teamId: string;
        invitationId: string;
    };
    query?: never;
    url: '/teams/{teamId}/invitations/{invitationId}';
};

export type DeleteTeamsByTeamIdInvitationsByInvitationIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type DeleteTeamsByTeamIdInvitationsByInvitationIdResponse = DeleteTeamsByTeamIdInvitationsByInvitationIdResponses[keyof DeleteTeamsByTeamIdInvitationsByInvitationIdResponses];

export type GetTeamsByTeamIdServersData = {
    body?: never;
    path: {
        teamId: string;
    };
    query?: never;
    url: '/teams/{teamId}/servers';
};

export type GetTeamsByTeamIdServersResponses = {
    /**
     * Successful response
     */
    200: {
        permissions: Array<{
            permission: ServerMember;
            server: TenantMcpServer;
        }>;
    };
};

export type GetTeamsByTeamIdServersResponse = GetTeamsByTeamIdServersResponses[keyof GetTeamsByTeamIdServersResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};