// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetServersData, GetServersResponses, PostServersData, PostServersResponses, DeleteServersBySlugData, DeleteServersBySlugResponses, GetServersBySlugData, GetServersBySlugResponses, PatchServersBySlugData, PatchServersBySlugResponses, PutServersBySlugData, PutServersBySlugResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List all MCP servers the caller has access to.
 */
export const getServers = <ThrowOnError extends boolean = true>(options?: Options<GetServersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetServersResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/servers',
        ...options
    });
};

/**
 * Create a new MCP server. Requires `slug` and `transportConfig`. All other fields are optional with sensible defaults. Read-only fields are silently ignored.
 */
export const postServers = <ThrowOnError extends boolean = true>(options?: Options<PostServersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostServersResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/servers',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete an MCP server.
 */
export const deleteServersBySlug = <ThrowOnError extends boolean = true>(options: Options<DeleteServersBySlugData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteServersBySlugResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/servers/{slug}',
        ...options
    });
};

/**
 * Get a single MCP server. The response body can be PUT back to update the server.
 */
export const getServersBySlug = <ThrowOnError extends boolean = true>(options: Options<GetServersBySlugData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetServersBySlugResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/servers/{slug}',
        ...options
    });
};

/**
 * Partially update an MCP server using JSON Merge Patch (RFC 7396). Send only the fields to change. Explicit `null` clears nullable fields (logoUrl, oauthMetadata, oauthClientConfiguration). Absent fields are untouched. Read-only fields are silently ignored.
 */
export const patchServersBySlug = <ThrowOnError extends boolean = true>(options: Options<PatchServersBySlugData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<PatchServersBySlugResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/servers/{slug}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Update an MCP server. Accepts the full server object from GET; read-only fields (id, tenantId, createdAt, updatedAt, lastToolRefreshAt) are silently ignored. Supports updating isEnabled, authorization, and config in a single call.
 */
export const putServersBySlug = <ThrowOnError extends boolean = true>(options: Options<PutServersBySlugData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutServersBySlugResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            },
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/servers/{slug}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};