// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { DeleteCredentialsByIdData, DeleteCredentialsByIdResponses, DeleteServersBySlugData, DeleteServersBySlugResponses, GetCredentialsByIdData, GetCredentialsByIdResponses, GetCredentialsByIdSecretData, GetCredentialsByIdSecretResponses, GetCredentialsData, GetCredentialsResponses, GetServersBySlugData, GetServersBySlugResponses, GetServersData, GetServersResponses, PatchServersBySlugData, PatchServersBySlugResponses, PostServersData, PostServersResponses, PutServersBySlugData, PutServersBySlugResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List all MCP servers the caller has access to.
 */
export const getServers = <ThrowOnError extends boolean = true>(options?: Options<GetServersData, ThrowOnError>) => (options?.client ?? client).get<GetServersResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/servers',
    ...options
});

/**
 * Create a new MCP server. Requires `slug` and `transportConfig`. All other fields are optional with sensible defaults. Read-only fields are silently ignored.
 */
export const postServers = <ThrowOnError extends boolean = true>(options?: Options<PostServersData, ThrowOnError>) => (options?.client ?? client).post<PostServersResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/servers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Delete an MCP server.
 */
export const deleteServersBySlug = <ThrowOnError extends boolean = true>(options: Options<DeleteServersBySlugData, ThrowOnError>) => (options.client ?? client).delete<DeleteServersBySlugResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/servers/{slug}',
    ...options
});

/**
 * Get a single MCP server. The response body can be PUT back to update the server.
 */
export const getServersBySlug = <ThrowOnError extends boolean = true>(options: Options<GetServersBySlugData, ThrowOnError>) => (options.client ?? client).get<GetServersBySlugResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/servers/{slug}',
    ...options
});

/**
 * Partially update an MCP server using JSON Merge Patch (RFC 7396). Send only the fields to change. Explicit `null` clears nullable fields (oauthMetadata, oauthClientConfiguration). Absent fields are untouched. Read-only fields are silently ignored.
 */
export const patchServersBySlug = <ThrowOnError extends boolean = true>(options: Options<PatchServersBySlugData, ThrowOnError>) => (options.client ?? client).patch<PatchServersBySlugResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/servers/{slug}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update an MCP server. Accepts the full server object from GET; read-only fields (id, tenantId, createdAt, updatedAt, lastToolRefreshAt) are silently ignored. Supports updating isEnabled, authorization, and config in a single call.
 */
export const putServersBySlug = <ThrowOnError extends boolean = true>(options: Options<PutServersBySlugData, ThrowOnError>) => (options.client ?? client).put<PutServersBySlugResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/servers/{slug}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getCredentials = <ThrowOnError extends boolean = true>(options?: Options<GetCredentialsData, ThrowOnError>) => (options?.client ?? client).get<GetCredentialsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/credentials',
    ...options
});

export const deleteCredentialsById = <ThrowOnError extends boolean = true>(options: Options<DeleteCredentialsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteCredentialsByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/credentials/{id}',
    ...options
});

export const getCredentialsById = <ThrowOnError extends boolean = true>(options: Options<GetCredentialsByIdData, ThrowOnError>) => (options.client ?? client).get<GetCredentialsByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/credentials/{id}',
    ...options
});

export const getCredentialsByIdSecret = <ThrowOnError extends boolean = true>(options: Options<GetCredentialsByIdSecretData, ThrowOnError>) => (options.client ?? client).get<GetCredentialsByIdSecretResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/credentials/{id}/secret',
    ...options
});
