// This file is auto-generated by @hey-api/openapi-ts

export type V2CreateServerRequest = {
  slug: Schema0;
  transportConfig: Schema1;
  description?: Schema18;
  authorization?: ServerAuthorization;
  oauthMetadata?: Schema23;
  oauthClientConfiguration?: Schema27;
  isEnabled?: Schema33;
  timeoutProtocol?: Schema34;
  timeoutTotal?: Schema35;
  resetTimeoutOnProgressNotification?: Schema36;
  isOutputCompressionEnabled?: Schema37;
  isOutputCompressionTransformEnabled?: Schema38;
  outputCompressionThresholdBytes?: Schema39;
  firewallRules?: Schema40;
  visibility?: ServerVisibility;
  id?: Schema43;
  tenantId?: Schema44;
  name?: Schema45;
  logoUrl?: Schema46;
  lastToolRefreshAt?: Schema47;
  createdAt?: Schema48;
  updatedAt?: Schema49;
};

export type HttpStreamingTransportConfig = {
  type: Schema2;
  url: Schema3;
  headers?: Schema4;
};

export type StdioTransportConfig = {
  type: Schema5;
  command: Schema6;
  dockerImage?: Schema7;
  env?: Schema8;
  transport: Schema9;
  httpPort?: Schema10;
  urlPath?: Schema11;
};

export type SseTransportConfig = {
  type: Schema12;
  url: Schema13;
  headers?: Schema14;
};

export type HostedTransportConfig = {
  type: Schema15;
  runtime: Schema16;
  env?: Schema17;
};

export type ServerAuthorization = {
  method: Schema20;
  credentialsScope: Schema21;
  apikeys?: Schema22;
};

export type ServerOAuthMetadata = {
  requiresAuthorization: Schema24;
  resource?: Schema25;
  as?: Schema26;
};

export type ServerOAuthClientConfiguration = {
  clientId?: Schema28;
  clientSecret?: Schema29;
  grantType: Schema30;
  clientAuthMethod: Schema31;
  scopes?: Schema32;
};

export type ServerVisibility = 'private' | 'organization';

export type V2UpdateServerRequest = {
  slug?: Schema51;
  description?: Schema52;
  authorization?: ServerAuthorization;
  transportConfig?: Schema54;
  oauthMetadata?: Schema55;
  oauthClientConfiguration?: Schema56;
  isEnabled?: Schema57;
  timeoutProtocol?: Schema58;
  timeoutTotal?: Schema59;
  resetTimeoutOnProgressNotification?: Schema60;
  isOutputCompressionEnabled?: Schema61;
  isOutputCompressionTransformEnabled?: Schema62;
  outputCompressionThresholdBytes?: Schema63;
  firewallRules?: Schema64;
  visibility?: ServerVisibility;
  id?: Schema66;
  tenantId?: Schema67;
  name?: Schema68;
  logoUrl?: Schema69;
  lastToolRefreshAt?: Schema70;
  createdAt?: Schema71;
  updatedAt?: Schema72;
};

export type V2PatchServerRequest = {
  [key in Schema73]?: Schema74;
};

export type Schema0 = string;

export type Schema1 = HttpStreamingTransportConfig | StdioTransportConfig | SseTransportConfig | HostedTransportConfig;

export type Schema2 = 'httpstreaming';

export type Schema3 = string;

export type Schema4 = Array<[string, string]>;

export type Schema5 = 'stdio';

export type Schema6 = string;

export type Schema7 = string;

export type Schema8 = Array<[string, string]>;

export type Schema9 = 'sse' | 'httpstreaming' | 'stdio';

export type Schema10 = number | null;

export type Schema11 = string | null;

export type Schema12 = 'sse';

export type Schema13 = string;

export type Schema14 = Array<[string, string]>;

export type Schema15 = 'hosted';

export type Schema16 = 'node24';

export type Schema17 = Array<[string, string]>;

export type Schema18 = string;

export type Schema19 = ServerAuthorization;

export type Schema20 = 'none' | 'oauth' | 'apikey';

export type Schema21 = 'server' | 'user';

export type Schema22 = Array<string>;

export type Schema23 = ServerOAuthMetadata | null;

export type Schema24 = boolean;

export type Schema25 = {
  id?: string;
  availableScopes?: Array<string>;
  metadataUrl?: string;
};

export type Schema26 = {
  issuer?: string;
  authorizeEndpoint?: string;
  deviceAuthorizationEndpoint?: string;
  tokenEndpoint?: string;
  extraAuthorizationParameters?: string;
  registrationEndpoint?: string;
  supportsPKCE?: boolean;
  supportedClientAuthMethods?: Array<string>;
  supportsDynamicClientRegistration?: boolean;
  noDynamicClientRegistrationReason?: string | null;
  serviceDocumentation?: string;
  metadataUrl?: string;
  availableScopes?: Array<string>;
};

export type Schema27 = ServerOAuthClientConfiguration | null;

export type Schema28 = string;

export type Schema29 = string;

export type Schema30 = 'authorization_code' | 'device_code';

export type Schema31 = 'client_secret_basic' | 'client_secret_post' | 'none' | string;

export type Schema32 = string;

export type Schema33 = boolean;

export type Schema34 = number;

export type Schema35 = number;

export type Schema36 = boolean;

export type Schema37 = boolean;

export type Schema38 = boolean;

export type Schema39 = number;

export type Schema40 = Array<Schema41>;

export type Schema41 = {
  /**
   * CEL representing the condition
   */
  condition: string;
  action: 'deny' | 'modify' | 'log';
};

export type Schema42 = ServerVisibility;

export type Schema43 = number;

export type Schema44 = string;

export type Schema45 = string;

export type Schema46 = string | null;

export type Schema47 = string | null;

export type Schema48 = string;

export type Schema49 = string;

export type Schema50 = string;

export type Schema51 = string;

export type Schema52 = string;

export type Schema53 = ServerAuthorization;

export type Schema54 =
  | HttpStreamingTransportConfig
  | StdioTransportConfig
  | SseTransportConfig
  | {
      type: 'self';
      id: string;
    }
  | HostedTransportConfig;

export type Schema55 = ServerOAuthMetadata | null;

export type Schema56 = ServerOAuthClientConfiguration | null;

export type Schema57 = boolean;

export type Schema58 = number;

export type Schema59 = number;

export type Schema60 = boolean;

export type Schema61 = boolean;

export type Schema62 = boolean;

export type Schema63 = number;

export type Schema64 = Array<Schema41>;

export type Schema65 = ServerVisibility;

export type Schema66 = number;

export type Schema67 = string;

export type Schema68 = string;

export type Schema69 = string | null;

export type Schema70 = string | null;

export type Schema71 = string;

export type Schema72 = string;

export type Schema73 = string;

export type Schema74 = unknown;

export type V2ListServersResponse = {
  servers: Schema75;
};

export type V2ServerDto = {
  id: Schema76;
  slug: Schema77;
  tenantId: Schema78;
  description: Schema79;
  authorization: ServerAuthorizationOutput;
  transportConfig: Schema83;
  oauthClientConfiguration: Schema100;
  oauthMetadata: Schema106;
  visibility: ServerVisibility;
  isEnabled: Schema110;
  lastToolRefreshAt: Schema111;
  timeoutProtocol: Schema112;
  timeoutTotal: Schema113;
  resetTimeoutOnProgressNotification: Schema114;
  isOutputCompressionEnabled: Schema115;
  isOutputCompressionTransformEnabled: Schema116;
  outputCompressionThresholdBytes: Schema117;
  firewallRules: Schema118;
  createdAt: Schema119;
  updatedAt: Schema120;
};

export type CredentialDtoV2 = {
  id: Schema122;
  tenantId: Schema123;
  scope: Schema124;
  userId: Schema125;
  profileId: Schema126;
  lastUsedAt: Schema127;
  authorizedAt: Schema128;
  type: Schema129;
  createdAt: Schema130;
  updatedAt: Schema131;
  serverSlug: Schema132;
  userSub: Schema133;
  userEmail: Schema134;
  userName: Schema135;
  profileName: Schema136;
};

export type ServerCredentialsOuth = {
  type: Schema137;
  tokenSet: Schema138;
};

export type ServerCredentialsApiKeys = {
  type: Schema139;
  apikeys: Schema140;
};

export type Schema75 = Array<V2ServerDto>;

export type Schema76 = number;

export type Schema77 = string;

export type Schema78 = string;

export type Schema79 = string;

export type Schema80 = 'none' | 'oauth' | 'apikey';

export type Schema81 = 'server' | 'user';

export type Schema82 = Array<string>;

export type Schema83 =
  | HttpStreamingTransportConfigOutput
  | StdioTransportConfigOutput
  | SseTransportConfigOutput
  | {
      type: 'self';
      id: string;
    }
  | HostedTransportConfigOutput;

export type Schema84 = 'httpstreaming';

export type Schema85 = string;

export type Schema86 = Array<[string, string]>;

export type Schema87 = 'stdio';

export type Schema88 = string;

export type Schema89 = string;

export type Schema90 = Array<[string, string]>;

export type Schema91 = 'sse' | 'httpstreaming' | 'stdio';

export type Schema92 = number | null;

export type Schema93 = string | null;

export type Schema94 = 'sse';

export type Schema95 = string;

export type Schema96 = Array<[string, string]>;

export type Schema97 = 'hosted';

export type Schema98 = 'node24';

export type Schema99 = Array<[string, string]>;

export type Schema100 = null | ServerOAuthClientConfigurationOutput;

export type Schema101 = string;

export type Schema102 = string;

export type Schema103 = 'authorization_code' | 'device_code';

export type Schema104 = 'client_secret_basic' | 'client_secret_post' | 'none' | string;

export type Schema105 = string;

export type Schema106 = null | ServerOAuthMetadataOutput;

export type Schema107 = boolean;

export type Schema108 = {
  id: string;
  availableScopes: Array<string>;
  metadataUrl: string;
};

export type Schema109 = {
  issuer: string;
  authorizeEndpoint: string;
  deviceAuthorizationEndpoint: string;
  tokenEndpoint: string;
  extraAuthorizationParameters: string;
  registrationEndpoint?: string;
  supportsPKCE: boolean;
  supportedClientAuthMethods: Array<string>;
  supportsDynamicClientRegistration: boolean;
  noDynamicClientRegistrationReason?: string | null;
  serviceDocumentation: string;
  metadataUrl: string;
  availableScopes: Array<string>;
};

export type Schema110 = boolean;

export type Schema111 = string | null;

export type Schema112 = number;

export type Schema113 = number;

export type Schema114 = boolean;

export type Schema115 = boolean;

export type Schema116 = boolean;

export type Schema117 = number;

export type Schema118 = Array<{
  /**
   * CEL representing the condition
   */
  condition: string;
  action: 'deny' | 'modify' | 'log';
}>;

export type Schema119 = string;

export type Schema120 = string;

export type Schema121 = {
  credentials: Array<CredentialDtoV2>;
};

export type Schema122 = string;

export type Schema123 = string;

export type Schema124 = 'server' | 'user' | 'profile';

export type Schema125 = number | null;

export type Schema126 = string | null;

export type Schema127 = string | null;

export type Schema128 = string;

export type Schema129 = 'oauth' | 'apikey';

export type Schema130 = string;

export type Schema131 = string;

export type Schema132 = string;

export type Schema133 = string | null;

export type Schema134 = string | null;

export type Schema135 = string | null;

export type Schema136 = string | null;

export type Schema137 = 'oauth';

export type Schema138 = {
  accessToken: string;
  accessTokenExpiresAt?: number;
  idToken?: string;
  refreshToken?: string;
};

export type Schema139 = 'apikey';

export type Schema140 = Array<[string, string]>;

export type ServerAuthorizationOutput = {
  method: Schema80;
  credentialsScope: Schema81;
  apikeys?: Schema82;
};

export type HttpStreamingTransportConfigOutput = {
  type: Schema84;
  url: Schema85;
  headers?: Schema86;
};

export type StdioTransportConfigOutput = {
  type: Schema87;
  command: Schema88;
  dockerImage?: Schema89;
  env?: Schema90;
  transport: Schema91;
  httpPort?: Schema92;
  urlPath?: Schema93;
};

export type SseTransportConfigOutput = {
  type: Schema94;
  url: Schema95;
  headers?: Schema96;
};

export type HostedTransportConfigOutput = {
  type: Schema97;
  runtime: Schema98;
  env?: Schema99;
};

export type ServerOAuthClientConfigurationOutput = {
  clientId: Schema101;
  clientSecret: Schema102;
  grantType: Schema103;
  clientAuthMethod: Schema104;
  scopes: Schema105;
};

export type ServerOAuthMetadataOutput = {
  requiresAuthorization: Schema107;
  resource?: Schema108;
  as?: Schema109;
};

export type GetServersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/servers';
};

export type GetServersResponses = {
  /**
   * Successful response
   */
  200: V2ListServersResponse;
};

export type GetServersResponse = GetServersResponses[keyof GetServersResponses];

export type PostServersData = {
  body?: V2CreateServerRequest;
  path?: never;
  query?: never;
  url: '/servers';
};

export type PostServersResponses = {
  /**
   * Successful response
   */
  200: V2ServerDto;
};

export type PostServersResponse = PostServersResponses[keyof PostServersResponses];

export type DeleteServersBySlugData = {
  body?: never;
  path: {
    slug: Schema50;
  };
  query?: never;
  url: '/servers/{slug}';
};

export type DeleteServersBySlugResponses = {
  /**
   * Successful response
   */
  200: unknown;
};

export type GetServersBySlugData = {
  body?: never;
  path: {
    slug: Schema50;
  };
  query?: never;
  url: '/servers/{slug}';
};

export type GetServersBySlugResponses = {
  /**
   * Successful response
   */
  200: V2ServerDto;
};

export type GetServersBySlugResponse = GetServersBySlugResponses[keyof GetServersBySlugResponses];

export type PatchServersBySlugData = {
  body?: V2PatchServerRequest;
  path: {
    slug: Schema50;
  };
  query?: never;
  url: '/servers/{slug}';
};

export type PatchServersBySlugResponses = {
  /**
   * Successful response
   */
  200: V2ServerDto;
};

export type PatchServersBySlugResponse = PatchServersBySlugResponses[keyof PatchServersBySlugResponses];

export type PutServersBySlugData = {
  body?: V2UpdateServerRequest;
  path: {
    slug: Schema50;
  };
  query?: never;
  url: '/servers/{slug}';
};

export type PutServersBySlugResponses = {
  /**
   * Successful response
   */
  200: V2ServerDto;
};

export type PutServersBySlugResponse = PutServersBySlugResponses[keyof PutServersBySlugResponses];

export type GetCredentialsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/credentials';
};

export type GetCredentialsResponses = {
  /**
   * Successful response
   */
  200: Schema121;
};

export type GetCredentialsResponse = GetCredentialsResponses[keyof GetCredentialsResponses];

export type DeleteCredentialsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/credentials/{id}';
};

export type DeleteCredentialsByIdResponses = {
  /**
   * Successful response
   */
  200: Schema121;
};

export type DeleteCredentialsByIdResponse = DeleteCredentialsByIdResponses[keyof DeleteCredentialsByIdResponses];

export type GetCredentialsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/credentials/{id}';
};

export type GetCredentialsByIdResponses = {
  /**
   * Successful response
   */
  200: CredentialDtoV2;
};

export type GetCredentialsByIdResponse = GetCredentialsByIdResponses[keyof GetCredentialsByIdResponses];

export type GetCredentialsByIdSecretData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/credentials/{id}/secret';
};

export type GetCredentialsByIdSecretResponses = {
  /**
   * Successful response
   */
  200: ServerCredentialsOuth | ServerCredentialsApiKeys;
};

export type GetCredentialsByIdSecretResponse =
  GetCredentialsByIdSecretResponses[keyof GetCredentialsByIdSecretResponses];

export type ClientOptions = {
  baseUrl: `${string}://${string}/api/v2` | (string & {});
};
