// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://{YOUR_ORG_ID}.gatana.ai/api/v2' | (string & {});
};

export type V2CreateServerRequest = {
    slug: Schema0;
    transportConfig: Schema1;
    description?: Schema23;
    authorization?: ServerAuthorization;
    oauthMetadata?: Schema28;
    oauthClientConfiguration?: Schema31;
    isEnabled?: Schema37;
    timeoutProtocol?: Schema38;
    timeoutTotal?: Schema39;
    resetTimeoutOnProgressNotification?: Schema40;
    isOutputCompressionEnabled?: Schema41;
    isOutputCompressionTransformEnabled?: Schema42;
    outputCompressionThresholdBytes?: Schema43;
    firewallRules?: Schema44;
    visibility?: ServerVisibility;
    id?: Schema47;
    tenantId?: Schema48;
    lastToolRefreshAt?: Schema49;
    createdAt?: Schema50;
    updatedAt?: Schema51;
};

export type HttpStreamingTransportConfig = {
    type: Schema2;
    url: Schema3;
    headers?: Schema4;
};

export type StdioTransportConfig = {
    type: Schema5;
    command: Schema6;
    dockerImage?: Schema7;
    env?: Schema8;
    transport: Schema9;
    httpPort?: Schema10;
    urlPath?: Schema11;
    healthCheck?: Schema12;
    limits?: Schema13;
};

export type SseTransportConfig = {
    type: Schema16;
    url: Schema17;
    headers?: Schema18;
};

export type HostedTransportConfig = {
    type: Schema19;
    runtime: Schema20;
    env?: Schema21;
    limits?: Schema22;
};

export type ServerAuthorization = {
    method: Schema25;
    credentialsScope: Schema26;
    apikeys?: Schema27;
};

export type ServerOAuthMetadata = {
    resource?: Schema29;
    as?: Schema30;
};

export type ServerOAuthClientConfiguration = {
    clientId?: Schema32;
    clientSecret?: Schema33;
    grantType: Schema34;
    clientAuthMethod: Schema35;
    scopes?: Schema36;
};

export type ServerVisibility = 'private' | 'organization';

export type V2UpdateServerRequest = {
    slug?: Schema53;
    description?: Schema54;
    authorization?: ServerAuthorization;
    transportConfig?: Schema56;
    oauthMetadata?: Schema57;
    oauthClientConfiguration?: Schema58;
    isEnabled?: Schema59;
    timeoutProtocol?: Schema60;
    timeoutTotal?: Schema61;
    resetTimeoutOnProgressNotification?: Schema62;
    isOutputCompressionEnabled?: Schema63;
    isOutputCompressionTransformEnabled?: Schema64;
    outputCompressionThresholdBytes?: Schema65;
    firewallRules?: Schema66;
    visibility?: ServerVisibility;
    id?: Schema68;
    tenantId?: Schema69;
    name?: Schema70;
    lastToolRefreshAt?: Schema71;
    createdAt?: Schema72;
    updatedAt?: Schema73;
};

export type V2PatchServerRequest = {
    [key in Schema74]?: Schema75;
};

export type Schema0 = string;

export type Schema1 = HttpStreamingTransportConfig | StdioTransportConfig | SseTransportConfig | HostedTransportConfig;

export type Schema2 = 'httpstreaming';

export type Schema3 = string;

export type Schema4 = Array<[
    string,
    string
]>;

export type Schema5 = 'stdio';

export type Schema6 = string;

export type Schema7 = string;

export type Schema8 = Array<[
    string,
    string
]>;

export type Schema9 = 'sse' | 'httpstreaming' | 'stdio';

export type Schema10 = number | null;

export type Schema11 = string | null;

export type Schema12 = {
    enabled: boolean;
    url?: string;
    delaySeconds: number | null;
    intervalSeconds: number | null;
    failureThreshold: number | null;
};

export type Schema13 = {
    cpu?: Schema14;
    memory?: Schema15;
} | null;

export type Schema14 = string;

export type Schema15 = string;

export type Schema16 = 'sse';

export type Schema17 = string;

export type Schema18 = Array<[
    string,
    string
]>;

export type Schema19 = 'hosted';

export type Schema20 = 'node24';

export type Schema21 = Array<[
    string,
    string
]>;

export type Schema22 = {
    cpu?: Schema14;
    memory?: Schema15;
} | null;

export type Schema23 = string;

export type Schema24 = ServerAuthorization;

export type Schema25 = 'none' | 'oauth' | 'apikey';

export type Schema26 = 'server' | 'user';

export type Schema27 = Array<string>;

export type Schema28 = ServerOAuthMetadata | null;

export type Schema29 = {
    id?: string;
    availableScopes?: Array<string>;
    metadataUrl?: string;
};

export type Schema30 = {
    issuer?: string;
    authorizeEndpoint?: string;
    deviceAuthorizationEndpoint?: string;
    tokenEndpoint?: string;
    extraAuthorizationParameters?: string;
    registrationEndpoint?: string;
    supportsPKCE?: boolean;
    supportedClientAuthMethods?: Array<string>;
    supportsDynamicClientRegistration?: boolean;
    noDynamicClientRegistrationReason?: string | null;
    serviceDocumentation?: string;
    metadataUrl?: string;
    availableScopes?: Array<string>;
};

export type Schema31 = ServerOAuthClientConfiguration | null;

export type Schema32 = string;

export type Schema33 = string;

export type Schema34 = 'authorization_code' | 'device_code';

export type Schema35 = 'client_secret_basic' | 'client_secret_post' | 'none' | string;

export type Schema36 = string;

export type Schema37 = boolean;

export type Schema38 = number;

export type Schema39 = number;

export type Schema40 = boolean;

export type Schema41 = boolean;

export type Schema42 = boolean;

export type Schema43 = number;

export type Schema44 = Array<Schema45>;

export type Schema45 = {
    /**
     * CEL representing the condition
     */
    condition: string;
    action: 'deny' | 'modify' | 'log';
};

export type Schema46 = ServerVisibility;

export type Schema47 = string;

export type Schema48 = string;

export type Schema49 = string | null;

export type Schema50 = string;

export type Schema51 = string;

export type Schema52 = string;

export type Schema53 = string;

export type Schema54 = string;

export type Schema55 = ServerAuthorization;

export type Schema56 = HttpStreamingTransportConfig | StdioTransportConfig | SseTransportConfig | {
    type: 'self';
    id: string;
} | HostedTransportConfig;

export type Schema57 = ServerOAuthMetadata | null;

export type Schema58 = ServerOAuthClientConfiguration | null;

export type Schema59 = boolean;

export type Schema60 = number;

export type Schema61 = number;

export type Schema62 = boolean;

export type Schema63 = boolean;

export type Schema64 = boolean;

export type Schema65 = number;

export type Schema66 = Array<Schema45>;

export type Schema67 = ServerVisibility;

export type Schema68 = string;

export type Schema69 = string;

export type Schema70 = string;

export type Schema71 = string | null;

export type Schema72 = string;

export type Schema73 = string;

export type Schema74 = string;

export type Schema75 = unknown;

export type V2ListServersResponse = {
    servers: Schema76;
};

export type V2ServerDto = Server;

export type Server = {
    id: Schema77;
    slug: Schema78;
    tenantId: Schema79;
    description: Schema80;
    authorization: ServerAuthorizationOutput;
    transportConfig: Schema84;
    oauthClientConfiguration: Schema106;
    oauthMetadata: Schema112;
    visibility: ServerVisibility;
    isEnabled: Schema115;
    lastToolRefreshAt: Schema116;
    timeoutProtocol: Schema117;
    timeoutTotal: Schema118;
    resetTimeoutOnProgressNotification: Schema119;
    isOutputCompressionEnabled: Schema120;
    isOutputCompressionTransformEnabled: Schema121;
    outputCompressionThresholdBytes: Schema122;
    firewallRules: Schema123;
    createdAt: Schema124;
    updatedAt: Schema125;
};

export type CredentialDtoV2 = {
    id: Schema127;
    tenantId: Schema128;
    scope: Schema129;
    userId: Schema130;
    profileId: Schema131;
    lastUsedAt: Schema132;
    authorizedAt: Schema133;
    type: Schema134;
    createdAt: Schema135;
    updatedAt: Schema136;
    serverSlug: Schema137;
    userEmail: Schema138;
    userName: Schema139;
    profileName: Schema140;
};

export type ServerCredentialsOuth = {
    type: Schema141;
    tokenSet: Schema142;
};

export type ServerCredentialsApiKeys = {
    type: Schema143;
    apikeys: Schema144;
};

export type Schema76 = Array<Server>;

export type Schema77 = string;

export type Schema78 = string;

export type Schema79 = string;

export type Schema80 = string;

export type Schema81 = 'none' | 'oauth' | 'apikey';

export type Schema82 = 'server' | 'user';

export type Schema83 = Array<string>;

export type Schema84 = HttpStreamingTransportConfigOutput | StdioTransportConfigOutput | SseTransportConfigOutput | {
    type: 'self';
    id: string;
} | HostedTransportConfigOutput;

export type Schema85 = 'httpstreaming';

export type Schema86 = string;

export type Schema87 = Array<[
    string,
    string
]>;

export type Schema88 = 'stdio';

export type Schema89 = string;

export type Schema90 = string;

export type Schema91 = Array<[
    string,
    string
]>;

export type Schema92 = 'sse' | 'httpstreaming' | 'stdio';

export type Schema93 = number | null;

export type Schema94 = string | null;

export type Schema95 = {
    enabled: boolean;
    url: string;
    delaySeconds: number | null;
    intervalSeconds: number | null;
    failureThreshold: number | null;
};

export type Schema96 = {
    cpu?: Schema97;
    memory?: Schema98;
} | null;

export type Schema97 = string;

export type Schema98 = string;

export type Schema99 = 'sse';

export type Schema100 = string;

export type Schema101 = Array<[
    string,
    string
]>;

export type Schema102 = 'hosted';

export type Schema103 = 'node24';

export type Schema104 = Array<[
    string,
    string
]>;

export type Schema105 = {
    cpu?: Schema97;
    memory?: Schema98;
} | null;

export type Schema106 = null | ServerOAuthClientConfigurationOutput;

export type Schema107 = string;

export type Schema108 = string;

export type Schema109 = 'authorization_code' | 'device_code';

export type Schema110 = 'client_secret_basic' | 'client_secret_post' | 'none' | string;

export type Schema111 = string;

export type Schema112 = null | ServerOAuthMetadataOutput;

export type Schema113 = {
    id: string;
    availableScopes: Array<string>;
    metadataUrl: string;
};

export type Schema114 = {
    issuer: string;
    authorizeEndpoint: string;
    deviceAuthorizationEndpoint: string;
    tokenEndpoint: string;
    extraAuthorizationParameters: string;
    registrationEndpoint?: string;
    supportsPKCE: boolean;
    supportedClientAuthMethods: Array<string>;
    supportsDynamicClientRegistration: boolean;
    noDynamicClientRegistrationReason?: string | null;
    serviceDocumentation: string;
    metadataUrl: string;
    availableScopes: Array<string>;
};

export type Schema115 = boolean;

export type Schema116 = string | null;

export type Schema117 = number;

export type Schema118 = number;

export type Schema119 = boolean;

export type Schema120 = boolean;

export type Schema121 = boolean;

export type Schema122 = number;

export type Schema123 = Array<{
    /**
     * CEL representing the condition
     */
    condition: string;
    action: 'deny' | 'modify' | 'log';
}>;

export type Schema124 = string;

export type Schema125 = string;

export type Schema126 = {
    credentials: Array<CredentialDtoV2>;
};

export type Schema127 = string;

export type Schema128 = string;

export type Schema129 = 'server' | 'user' | 'profile';

export type Schema130 = string | null;

export type Schema131 = string | null;

export type Schema132 = string | null;

export type Schema133 = string;

export type Schema134 = 'oauth' | 'apikey';

export type Schema135 = string;

export type Schema136 = string;

export type Schema137 = string;

export type Schema138 = string | null;

export type Schema139 = string | null;

export type Schema140 = string | null;

export type Schema141 = 'oauth';

export type Schema142 = {
    accessToken: string;
    accessTokenExpiresAt?: number;
    idToken?: string;
    refreshToken?: string;
};

export type Schema143 = 'apikey';

export type Schema144 = Array<[
    string,
    string
]>;

export type ServerAuthorizationOutput = {
    method: Schema81;
    credentialsScope: Schema82;
    apikeys?: Schema83;
};

export type HttpStreamingTransportConfigOutput = {
    type: Schema85;
    url: Schema86;
    headers?: Schema87;
};

export type StdioTransportConfigOutput = {
    type: Schema88;
    command: Schema89;
    dockerImage?: Schema90;
    env?: Schema91;
    transport: Schema92;
    httpPort?: Schema93;
    urlPath?: Schema94;
    healthCheck?: Schema95;
    limits?: Schema96;
};

export type SseTransportConfigOutput = {
    type: Schema99;
    url: Schema100;
    headers?: Schema101;
};

export type HostedTransportConfigOutput = {
    type: Schema102;
    runtime: Schema103;
    env?: Schema104;
    limits?: Schema105;
};

export type ServerOAuthClientConfigurationOutput = {
    clientId: Schema107;
    clientSecret: Schema108;
    grantType: Schema109;
    clientAuthMethod: Schema110;
    scopes: Schema111;
};

export type ServerOAuthMetadataOutput = {
    resource?: Schema113;
    as?: Schema114;
};

export type GetServersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/servers';
};

export type GetServersResponses = {
    /**
     * Successful response
     */
    200: V2ListServersResponse;
};

export type GetServersResponse = GetServersResponses[keyof GetServersResponses];

export type PostServersData = {
    body?: V2CreateServerRequest;
    path?: never;
    query?: never;
    url: '/servers';
};

export type PostServersResponses = {
    /**
     * Successful response
     */
    200: Server;
};

export type PostServersResponse = PostServersResponses[keyof PostServersResponses];

export type DeleteServersBySlugData = {
    body?: never;
    path: {
        slug: Schema52;
    };
    query?: never;
    url: '/servers/{slug}';
};

export type DeleteServersBySlugResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type GetServersBySlugData = {
    body?: never;
    path: {
        slug: Schema52;
    };
    query?: never;
    url: '/servers/{slug}';
};

export type GetServersBySlugResponses = {
    /**
     * Successful response
     */
    200: Server;
};

export type GetServersBySlugResponse = GetServersBySlugResponses[keyof GetServersBySlugResponses];

export type PatchServersBySlugData = {
    body?: V2PatchServerRequest;
    path: {
        slug: Schema52;
    };
    query?: never;
    url: '/servers/{slug}';
};

export type PatchServersBySlugResponses = {
    /**
     * Successful response
     */
    200: Server;
};

export type PatchServersBySlugResponse = PatchServersBySlugResponses[keyof PatchServersBySlugResponses];

export type PutServersBySlugData = {
    body?: V2UpdateServerRequest;
    path: {
        slug: Schema52;
    };
    query?: never;
    url: '/servers/{slug}';
};

export type PutServersBySlugResponses = {
    /**
     * Successful response
     */
    200: Server;
};

export type PutServersBySlugResponse = PutServersBySlugResponses[keyof PutServersBySlugResponses];

export type GetCredentialsData = {
    body?: never;
    path?: never;
    query?: {
        serverId?: string;
    };
    url: '/credentials';
};

export type GetCredentialsResponses = {
    /**
     * Successful response
     */
    200: Schema126;
};

export type GetCredentialsResponse = GetCredentialsResponses[keyof GetCredentialsResponses];

export type DeleteCredentialsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/credentials/{id}';
};

export type DeleteCredentialsByIdResponses = {
    /**
     * Successful response
     */
    200: Schema126;
};

export type DeleteCredentialsByIdResponse = DeleteCredentialsByIdResponses[keyof DeleteCredentialsByIdResponses];

export type GetCredentialsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/credentials/{id}';
};

export type GetCredentialsByIdResponses = {
    /**
     * Successful response
     */
    200: CredentialDtoV2;
};

export type GetCredentialsByIdResponse = GetCredentialsByIdResponses[keyof GetCredentialsByIdResponses];

export type GetCredentialsByIdSecretData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/credentials/{id}/secret';
};

export type GetCredentialsByIdSecretResponses = {
    /**
     * Successful response
     */
    200: ServerCredentialsOuth | ServerCredentialsApiKeys;
};

export type GetCredentialsByIdSecretResponse = GetCredentialsByIdSecretResponses[keyof GetCredentialsByIdSecretResponses];
