// This file is auto-generated by @hey-api/openapi-ts

export type V2CreateServerRequest = {
    slug: string;
    transportConfig: Schema0;
    description?: string;
    authorization?: ServerAuthorization;
    oauthMetadata?: ServerOAuthMetadata | null;
    oauthClientConfiguration?: ServerOAuthClientConfiguration | null;
    isEnabled?: boolean;
    timeoutProtocol?: number;
    timeoutTotal?: number;
    resetTimeoutOnProgressNotification?: boolean;
    id?: number;
    tenantId?: string;
    name?: string;
    logoUrl?: string | null;
    lastToolRefreshAt?: string | null;
    createdAt?: string;
    updatedAt?: string;
};

export type HttpStreamingTransportConfig = {
    type: 'httpstreaming';
    url: string;
    headers?: Array<[
        string,
        string
    ]>;
};

export type StdioTransportConfig = {
    type: 'stdio';
    command: string;
    dockerImage?: string;
    env?: Array<[
        string,
        string
    ]>;
    transport: 'sse' | 'httpstreaming' | 'stdio';
    httpPort?: number | null;
    urlPath?: string | null;
};

export type SseTransportConfig = {
    type: 'sse';
    url: string;
    headers?: Array<[
        string,
        string
    ]>;
};

export type HostedTransportConfig = {
    type: 'hosted';
    runtime: 'node24';
    env?: Array<[
        string,
        string
    ]>;
};

export type ServerAuthorization = {
    method: 'none' | 'oauth' | 'apikey';
    credentialsScope: 'server' | 'user';
    apikeys?: Array<string>;
};

export type ServerOAuthMetadata = {
    requiresAuthorization: boolean;
    resource?: {
        id?: string;
        availableScopes?: Array<string>;
        metadataUrl?: string;
    };
    as?: {
        issuer?: string;
        authorizeEndpoint?: string;
        deviceAuthorizationEndpoint?: string;
        tokenEndpoint?: string;
        extraAuthorizationParameters?: string;
        registrationEndpoint?: string;
        supportsPKCE?: boolean;
        supportedClientAuthMethods?: Array<string>;
        supportsDynamicClientRegistration?: boolean;
        noDynamicClientRegistrationReason?: string | null;
        serviceDocumentation?: string;
        metadataUrl?: string;
        availableScopes?: Array<string>;
    };
};

export type ServerOAuthClientConfiguration = {
    clientId?: string;
    clientSecret?: string;
    grantType: 'authorization_code' | 'device_code';
    clientAuthMethod: 'client_secret_basic' | 'client_secret_post' | 'none' | string;
    scopes?: string;
};

export type V2UpdateServerRequest = {
    slug?: string;
    description?: string;
    authorization?: ServerAuthorization;
    transportConfig?: Schema0;
    oauthMetadata?: ServerOAuthMetadata | null;
    oauthClientConfiguration?: ServerOAuthClientConfiguration | null;
    isEnabled?: boolean;
    timeoutProtocol?: number;
    timeoutTotal?: number;
    resetTimeoutOnProgressNotification?: boolean;
    id?: number;
    tenantId?: string;
    name?: string;
    logoUrl?: string | null;
    lastToolRefreshAt?: string | null;
    createdAt?: string;
    updatedAt?: string;
};

export type V2PatchServerRequest = {
    [key: string]: unknown;
};

export type Schema0 = HttpStreamingTransportConfig | StdioTransportConfig | SseTransportConfig | {
    type: 'self';
    id: string;
} | HostedTransportConfig;

export type Schema1 = string;

export type V2ListServersResponse = {
    servers: Array<V2ServerDto>;
};

export type V2ServerDto = {
    id: number;
    slug: string;
    tenantId: string;
    description: string;
    authorization: ServerAuthorizationOutput;
    transportConfig: HttpStreamingTransportConfigOutput | StdioTransportConfigOutput | SseTransportConfigOutput | {
        type: 'self';
        id: string;
    } | HostedTransportConfigOutput;
    oauthClientConfiguration: null | ServerOAuthClientConfigurationOutput;
    oauthMetadata: null | ServerOAuthMetadataOutput;
    isEnabled: boolean;
    lastToolRefreshAt: string | null;
    timeoutProtocol: number;
    timeoutTotal: number;
    resetTimeoutOnProgressNotification: boolean;
    createdAt: string;
    updatedAt: string;
};

export type ServerAuthorizationOutput = {
    method: 'none' | 'oauth' | 'apikey';
    credentialsScope: 'server' | 'user';
    apikeys?: Array<string>;
};

export type HttpStreamingTransportConfigOutput = {
    type: 'httpstreaming';
    url: string;
    headers?: Array<[
        string,
        string
    ]>;
};

export type StdioTransportConfigOutput = {
    type: 'stdio';
    command: string;
    dockerImage?: string;
    env?: Array<[
        string,
        string
    ]>;
    transport: 'sse' | 'httpstreaming' | 'stdio';
    httpPort?: number | null;
    urlPath?: string | null;
};

export type SseTransportConfigOutput = {
    type: 'sse';
    url: string;
    headers?: Array<[
        string,
        string
    ]>;
};

export type HostedTransportConfigOutput = {
    type: 'hosted';
    runtime: 'node24';
    env?: Array<[
        string,
        string
    ]>;
};

export type ServerOAuthClientConfigurationOutput = {
    clientId: string;
    clientSecret: string;
    grantType: 'authorization_code' | 'device_code';
    clientAuthMethod: 'client_secret_basic' | 'client_secret_post' | 'none' | string;
    scopes: string;
};

export type ServerOAuthMetadataOutput = {
    requiresAuthorization: boolean;
    resource?: {
        id: string;
        availableScopes: Array<string>;
        metadataUrl: string;
    };
    as?: {
        issuer: string;
        authorizeEndpoint: string;
        deviceAuthorizationEndpoint: string;
        tokenEndpoint: string;
        extraAuthorizationParameters: string;
        registrationEndpoint?: string;
        supportsPKCE: boolean;
        supportedClientAuthMethods: Array<string>;
        supportsDynamicClientRegistration: boolean;
        noDynamicClientRegistrationReason?: string | null;
        serviceDocumentation: string;
        metadataUrl: string;
        availableScopes: Array<string>;
    };
};

export type GetServersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/servers';
};

export type GetServersResponses = {
    /**
     * Successful response
     */
    200: V2ListServersResponse;
};

export type GetServersResponse = GetServersResponses[keyof GetServersResponses];

export type PostServersData = {
    body?: V2CreateServerRequest;
    path?: never;
    query?: never;
    url: '/servers';
};

export type PostServersResponses = {
    /**
     * Successful response
     */
    200: V2ServerDto;
};

export type PostServersResponse = PostServersResponses[keyof PostServersResponses];

export type DeleteServersBySlugData = {
    body?: never;
    path: {
        slug: Schema1;
    };
    query?: never;
    url: '/servers/{slug}';
};

export type DeleteServersBySlugResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type GetServersBySlugData = {
    body?: never;
    path: {
        slug: Schema1;
    };
    query?: never;
    url: '/servers/{slug}';
};

export type GetServersBySlugResponses = {
    /**
     * Successful response
     */
    200: V2ServerDto;
};

export type GetServersBySlugResponse = GetServersBySlugResponses[keyof GetServersBySlugResponses];

export type PatchServersBySlugData = {
    body?: V2PatchServerRequest;
    path: {
        slug: Schema1;
    };
    query?: never;
    url: '/servers/{slug}';
};

export type PatchServersBySlugResponses = {
    /**
     * Successful response
     */
    200: V2ServerDto;
};

export type PatchServersBySlugResponse = PatchServersBySlugResponses[keyof PatchServersBySlugResponses];

export type PutServersBySlugData = {
    body?: V2UpdateServerRequest;
    path: {
        slug: Schema1;
    };
    query?: never;
    url: '/servers/{slug}';
};

export type PutServersBySlugResponses = {
    /**
     * Successful response
     */
    200: V2ServerDto;
};

export type PutServersBySlugResponse = PutServersBySlugResponses[keyof PutServersBySlugResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v2` | (string & {});
};